-- Insert completo com 600 jogos Atari
-- Composicao: 472 Atari 2600 + 69 Atari 5200 + 59 Atari 7800
-- Estrutura alvo: jogos(titulo, genero, desenvolvedora, publicadora, ano_lancamento, classificacao_indicativa, modo_jogo, descricao)
-- Observacao: sua tabela nao possui coluna plataforma; por isso a plataforma foi registrada na descricao.

INSERT INTO jogos (titulo, genero, desenvolvedora, publicadora, ano_lancamento, classificacao_indicativa, modo_jogo, descricao)
VALUES
('3-D Tic-Tac-Toe', 'Estrategia', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Adventure', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Air-Sea Battle', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Alpha Beam with Ernie', 'Educacional', 'Atari, Inc. / Children''s Computer Workshop', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Asteroids', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Atari Video Cube', 'Puzzle', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Backgammon', 'Tabuleiro', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Basic Math', 'Educacional', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('BASIC Programming', 'Programacao', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Basketball', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Battlezone', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Berzerk', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Big Bird''s Egg Catch', 'Educacional', 'Atari, Inc. / Children''s Computer Workshop', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Blackjack', 'Cartas', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('BMX Air Master', 'Esporte', 'TNT Games', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Bowling', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Brain Games', 'Puzzle', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Breakout', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Canyon Bomber', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Casino', 'Cartas', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Centipede', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Circus Atari', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Codebreaker', 'Puzzle', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Combat', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Concentration', 'Puzzle', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Cookie Monster Munch', 'Educacional', 'Atari, Inc. / Children''s Computer Workshop', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Crazy Climber', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Crossbow', 'Light gun', 'Atari Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Crystal Castles', 'Maze', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Dark Chambers', 'Acao', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Defender', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Demons to Diamonds', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Desert Falcon', 'Shooter', 'Atari Corporation', 'Atari Corporation', 1987, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Dig Dug', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Dodge Em', 'Corrida', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Donald Duck''s Speedboat', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Double Dunk', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('E.T. the Extra-Terrestrial', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Fatal Run', 'Corrida', 'Atari Corporation', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Flag Capture', 'Puzzle', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Football', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Galaxian', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Golf', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Gravitar', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Gremlins', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Hangman', 'Palavras', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Haunted House', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Home Run', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Human Cannonball', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Ikari Warriors', 'Shooter', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Indy 500', 'Corrida', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Joust', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Jr. Pac-Man', 'Arcade', 'Atari Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Jungle Hunt', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Kangaroo', 'Plataforma', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Klax', 'Puzzle', 'Atari Corporation', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Krull', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Mario Bros.', 'Plataforma', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Math Gran Prix', 'Educacional', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Maze Craze', 'Maze', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Midnight Magic', 'Pinball', 'Atari Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Millipede', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Miniature Golf', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Missile Command', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Moon Patrol', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('MotoRodeo', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Ms. Pac-Man', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Night Driver', 'Corrida', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Obelix', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Off the Wall', 'Arcade', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Oscar''s Trash Race', 'Educacional', 'Atari, Inc. / Children''s Computer Workshop', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Othello', 'Tabuleiro', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Outlaw', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Pac-Man', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Pele''s Soccer', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Pengo', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Phoenix', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Pigs in Space', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Pole Position', 'Corrida', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Quadrun', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Radar Lock', 'Shooter', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Raiders of the Lost Ark', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('RealSports Baseball', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('RealSports Boxing', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1987, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('RealSports Football', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('RealSports Soccer', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('RealSports Tennis', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('RealSports Volleyball', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Road Runner', 'Acao', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Secret Quest', 'Aventura', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Sentinel', 'Light gun', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Sky Diver', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Slot Machine', 'Cassino', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Slot Racers', 'Maze', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Snoopy and the Red Baron', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Solaris', 'Shooter', 'Atari Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Sorcerer''s Apprentice', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Space Invaders', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Space War', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1978, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Sprint Master', 'Corrida', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Stargate', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Star Raiders', 'Simulador', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Star Ship', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Steeplechase', 'Esporte', 'Atari, Inc.', 'Sears Tele-Games', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Stellar Track', 'Estrategia', 'Atari, Inc.', 'Sears Tele-Games', 1981, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Street Racer', 'Corrida', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Submarine Commander', 'Simulador', 'Atari, Inc.', 'Sears Tele-Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Super Baseball', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Super Breakout', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Super Football', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Superman', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Surround', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Swordquest: EarthWorld', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Swordquest: FireWorld', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Swordquest: WaterWorld', 'Aventura', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Tempest', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Track & Field', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Video Checkers', 'Tabuleiro', 'Atari, Inc.', 'Atari, Inc.', 1980, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Video Chess', 'Tabuleiro', 'Atari, Inc.', 'Atari, Inc.', 1979, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Video Olympics', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1977, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Warlords', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Yars'' Revenge', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Xenophobe', 'Acao', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Pitfall!', 'Plataforma', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Pitfall II: Lost Caverns', 'Plataforma', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('River Raid', 'Shooter', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Kaboom!', 'Acao', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Laser Blast', 'Shooter', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Freeway', 'Acao', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Stampede', 'Acao', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Skiing', 'Esporte', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Boxing', 'Esporte', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Fishing Derby', 'Esporte', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Ice Hockey', 'Esporte', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Tennis', 'Esporte', 'Activision', 'Activision', 1981, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Megamania', 'Shooter', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Barnstorming', 'Acao', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Chopper Command', 'Shooter', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Grand Prix', 'Corrida', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Spider Fighter', 'Shooter', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Seaquest', 'Shooter', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Oink!', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Dolphin', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Enduro', 'Corrida', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Keystone Kapers', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Plaque Attack', 'Shooter', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Beamrider', 'Shooter', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('H.E.R.O.', 'Acao', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Pressure Cooker', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Private Eye', 'Aventura', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Robot Tank', 'Shooter', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Space Shuttle: A Journey into Space', 'Simulador', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Cosmic Ark', 'Shooter', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Demon Attack', 'Shooter', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Atlantis', 'Shooter', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Dragonfire', 'Acao', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Moonsweeper', 'Shooter', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('No Escape!', 'Acao', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Quick Step', 'Acao', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Riddle of the Sphinx', 'Aventura', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Star Voyager', 'Shooter', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Subterranea', 'Shooter', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Fathom', 'Aventura', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Donkey Kong', 'Plataforma', 'Coleco', 'Coleco', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Donkey Kong Junior', 'Plataforma', 'Coleco', 'Coleco', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Carnival', 'Shooter', 'Coleco', 'Coleco', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Venture', 'Acao', 'Coleco', 'Coleco', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Mouse Trap', 'Maze', 'Coleco', 'Coleco', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Smurf: Rescue in Gargamel''s Castle', 'Plataforma', 'Coleco', 'Coleco', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Zaxxon', 'Shooter', 'Coleco', 'Coleco', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Q*bert', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Frogger', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Popeye', 'Plataforma', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Star Wars: The Empire Strikes Back', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Star Wars: Jedi Arena', 'Acao', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Star Wars: Return of the Jedi Death Star Battle', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('James Bond 007', 'Acao', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Montezuma''s Revenge', 'Plataforma', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Gyruss', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Tutankham', 'Maze', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Mr. Do!', 'Arcade', 'Coleco', 'Coleco', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Congo Bongo', 'Plataforma', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Burgertime', 'Arcade', 'M Network', 'M Network', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Bump n Jump', 'Corrida', 'M Network', 'M Network', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Frogs and Flies', 'Acao', 'M Network', 'M Network', 1982, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Masters of the Universe: The Power of He-Man', 'Acao', 'M Network', 'M Network', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Air Raiders', 'Shooter', 'M Network', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Dark Cavern', 'Shooter', 'M Network', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Froggie', 'Acao', 'Tigervision', 'Tigervision', 1983, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Polaris', 'Shooter', 'Tigervision', 'Tigervision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('River Patrol', 'Acao', 'Tigervision', 'Tigervision', 1984, 'Sem classificacao', 'Single-player e Multiplayer', 'Jogo lancado para Atari 2600.'),
('Springer', 'Plataforma', 'Tigervision', 'Tigervision', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Miner 2049er', 'Plataforma', 'Tigervision', 'Tigervision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Miner 2049er Volume II', 'Plataforma', 'Tigervision', 'Tigervision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Halloween', 'Terror', 'MicroGraphicImage', 'Wizard Video', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('The Texas Chainsaw Massacre', 'Terror', 'VSS', 'Wizard Video', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Custer''s Revenge', 'Adulto', 'Mystique', 'Mystique', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Beat Em & Eat Em', 'Adulto', 'Mystique', 'Mystique', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 2600.'),
('Acid Drop', 'Estrategia', 'Salu Ltd', 'Salu Ltd', 1992, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Activision Decathlon', 'Esporte', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Adventures of Tron', 'Acao', 'APh Technological Consulting', 'M Network', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Airlock', 'Acao', 'Data Age', 'Data Age', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Air Raid', 'Acao', 'MenAVision', 'MenAVision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Alien', 'Maze', 'Fox Video Games', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Amidar', 'Acao', 'Parker Brothers', 'Parker Brothers', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Armor Ambush', 'Acao / Corrida', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Artillery Duel', 'Estrategia', 'Action Graphics', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Assault', 'Acao', 'Bomb', 'Bomb', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Astroblast', 'Acao', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Astrowar', 'Acao', 'Dimax / Sinmax', 'Dimax / Sinmax', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Atlantis II', 'Acao', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bachelor Party', 'Adulto / Acao', 'Mystique', 'PlayAround', 1982, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bank Heist', 'Acao / Corrida', 'Fox Video Games', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Base Attack', 'Shooter', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Beany Bopper', 'Acao', 'Sirius Software', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Beat Em and Eat Em', 'Adulto / Acao', 'Mystique', 'PlayAround', 1982, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Berenstain Bears', 'Educacional', 'Coleco', 'Coleco', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bermuda Triangle', 'Acao', 'Data Age', 'Data Age', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Birthday Mania', 'Acao', 'Robert Anthony Tokar', 'Personal Games Company', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Blue Print', 'Acao', 'CBS Electronics', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bobby is Going Home', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Boing!', 'Acao', 'First Star Software', 'First Star Software', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bridge', 'Estrategia', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Buck Rogers: Planet of Zoom', 'Acao', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bugs', 'Acao', 'Data Age', 'Data Age', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Bumper Bash', 'Acao', 'Spectravision', 'Spectravision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('BurgerTime', 'Acao', 'Mattel Electronics', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Burning Desire', 'Adulto / Acao', 'PlayAround', 'PlayAround', 1983, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cakewalk', 'Acao', 'CommaVid', 'CommaVid', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('California Games', 'Esporte', 'Epyx', 'Epyx', 1988, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cat Trax', 'Acao', 'UA Limited', 'RGA International', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Challenge', 'Acao', 'Funvision', 'Funvision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Challenge of Nexar', 'Acao', 'Sirius Software', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Chase the Chuck Wagon', 'Acao', 'TMQ Software', 'Spectravision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Checkers', 'Estrategia', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('China Syndrome', 'Acao', 'Spectravision', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Chuck Norris Superkicks', 'Acao', 'Xonox', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Coconuts', 'Acao', 'Telesys', 'Telesys', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Commando', 'Acao', 'Imagineering', 'Activision', 1988, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Commando Raid', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Communist Mutants from Space', 'Acao', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Condor Attack', 'Acao', 'Ultravision', 'Ultravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Confrontation', 'Estrategia', 'Answer Software', 'Answer Software', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cosmic Commuter', 'Acao', 'Activision', 'Activision', 1985, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cosmic Creeps', 'Acao', 'Telesys', 'Telesys', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cosmic Swarm', 'Acao', 'CommaVid', 'CommaVid', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Crackpots', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Crash Dive', 'Acao', 'Fox Video Games', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cross Force', 'Acao', 'Spectravision', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Crypts of Chaos', 'Aventura / RPG', 'Fox Video Games', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Cubicolor', 'Estrategia', 'Imagic', 'Rob Fulop', 1986, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Custers Revenge', 'Adulto / Western', 'Mystique', 'Mystique', 1982, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Dancing Plate', 'Acao', 'Bit Corporation', 'Bit Corporation', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Deadly Duck', 'Acao', 'Sirius Software', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Death Trap', 'Acao / Estrategia', 'Avalon Hill', 'Avalon Hill', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Demolition Herby', 'Acao', 'Telesys', 'Telesys', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Dice Puzzle', 'Puzzle', 'Panda', 'Panda', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Double Dragon', 'Acao', 'Imagineering', 'Activision', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Dragonstomper', 'RPG', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Dragster', 'Corrida', 'Activision', 'Activision', 1980, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Earth Dies Screaming', 'Acao', 'Sirius Software', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Eddy Langfinger, der Museumsdieb', 'Acao', 'Quelle', 'Quelle', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Eggomania', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Elis Ladder', 'Educacional', 'Simage', 'Simage', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Encounter at L-5', 'Acao', 'Data Age', 'Data Age', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Entombed', 'Acao / Estrategia', 'Western Technologies', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Escape from the Mindmaster', 'Aventura', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Espial', 'Acao', 'Orca Corporation', 'Tigervision', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Exocet', 'Acao', 'Panda', 'Panda', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Extra Terrestrials', 'Acao', 'Herman Quast', 'Skill Screen Games', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fantastic Voyage', 'Shooter', 'Sirius Software', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Farmyard Fun', 'Acao', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fast Eddie', 'Acao', 'Sirius Software', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fast Food', 'Acao', 'Telesys', 'Telesys', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Final Approach', 'Simulacao / Estrategia', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fireball', 'Acao', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Firebug', 'Acao', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fire Fighter', 'Acao', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Fire Fly', 'Acao', 'Mythicon', 'Mythicon', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Flash Gordon', 'Acao', 'Sirius Software', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Forest', 'Acao', 'Sancho / Tangs Electronic', 'Sancho / Tangs Electronic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Frankensteins Monster', 'Acao', 'Data Age', 'Data Age', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Frisco', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Official Frogger', 'Acao', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Frogger II: ThreeeDeep!', 'Acao', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Front Line', 'Acao', 'Individeo', 'Coleco', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Frostbite', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gamma-Attack', 'Acao', 'Gammation', 'Gammation', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gangster Alley', 'Acao', 'Spectravision', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gas Hog', 'Acao', 'Spectravision', 'Spectravision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gauntlet', 'Acao', 'Answer Software', 'Answer Software', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ghostbusters', 'Acao', 'Activision', 'Activision', 1985, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ghostbusters II', 'Acao', 'Activision', 'Salu Ltd', 1990, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ghost Manor', 'Acao', 'Xonox', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('G.I. Joe: Cobra Strike', 'Acao', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gigolo', 'Adulto', 'PlayAround', 'PlayAround', 1982, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Glacier Patrol', 'Acao', 'VSS', 'Telegames', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Glib', 'Estrategia', 'Qualtronic Devices', 'Selchow and Righter', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Go Go Home', 'Acao', 'Gem International Corporation', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gopher', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Gorf', 'Acao', 'Roklan Corporation', 'CBS Electronics', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Great Escape', 'Acao', 'Bomb', 'Bomb', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Guardian', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Inca Gold', 'Acao', 'Funvision', 'Funvision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Infiltrate', 'Acao / Estrategia', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('International Soccer', 'Esporte', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('I.Q. Memory Teaser', 'Puzzle', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Jawbreaker', 'Acao', 'On-Line Systems', 'Tigervision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Journey Escape', 'Acao', 'Data Age', 'Data Age', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Karate', 'Acao', 'Ultravision', 'Ultravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Killer Satellites', 'Acao', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('King Kong', 'Acao', 'Software Electronics', 'Tigervision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Knight on the Town', 'Adulto / Acao', 'PlayAround', 'PlayAround', 1982, '18', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Kool-Aid Man', 'Acao', 'Mattel Electronics', 'M Network', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Kung-Fu Master', 'Acao', 'Imagineering', 'Activision', 1987, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Laser Gates', 'Acao', 'Imagic / VentureVision', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Lilly Adventure', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Lochjaw', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Lock n Chase', 'Acao', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('London Blitz', 'Estrategia', 'Avalon Hill', 'Avalon Hill', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Lost Luggage', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('M.A.D.', 'Acao', 'Western Technologies', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('MagiCard', 'Programacao', 'CommaVid', 'CommaVid', 1981, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Malagai', 'Acao', 'Answer Software', 'Answer Software', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mangia', 'Acao', 'Spectravision', 'Spectravision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Marauder', 'Acao', 'On-Line Systems', 'Tigervision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Marine Wars', 'Acao', 'Digivision', 'Konami', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('M*A*S*H', 'Acao', 'Fox Video Games', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Master Builder', 'Acao', 'Spectravision', 'Spectravision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mazy Match', 'Puzzle', 'Nao informado', 'Nao informado', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('MegaBoy', 'Educacional', 'Dynacom', 'Dynacom', 1990, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mega Force', 'Acao', 'Fox Video Games', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mines of Minos', 'Acao', 'CommaVid', 'CommaVid', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Missile Control', 'Acao', 'Video Gems', 'Video Gems', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mission 3000 A.D.', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mission Survive', 'Acao', 'Video Gems', 'Video Gems', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mogul Maniac', 'Acao / Simulacao / Esporte', 'Video Soft', 'Amiga', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Montezumas Revenge: Starring Panama Joe', 'Acao', 'James Wickstead Design Associates', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Motocross', 'Corrida / Esporte', 'Quelle', 'Quelle', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Motocross Racer', 'Corrida', 'Xonox', 'Xonox', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mountain King', 'Acao', 'VSS', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mr. Dos Castle', 'Acao', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Mr. Postman', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Music Machine', 'Acao / Educacional', 'Christian Software Development', 'Sparrow', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('My Golf', 'Esporte', 'Imagineering', 'HES', 1990, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Name This Game', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Nightmare', 'Acao', 'Sancho / Tangs Electronic', 'Sancho / Tangs Electronic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Nuts', 'Acao', 'Technovision', 'Technovision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Off Your Rocker', 'Acao', 'Amiga', 'Pleasant Valley Video', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Omega Race', 'Acao', 'CBS Electronics', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Open Sesame', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Out of Control', 'Acao / Corrida', 'Avalon Hill', 'Avalon Hill', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Panda Chase', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Parachute', 'Acao', 'Gem International Corporation', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Party Mix', 'Acao / Corrida', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Pete Rose Baseball', 'Esporte', 'Imagineering', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Phantom Tank', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Pharaohs Curse', 'Acao', 'TechnoVision', 'TechnoVision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Phaser Patrol', 'Acao', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Pick n Pile', 'Estrategia', 'Ubisoft', 'Salu Ltd', 1990, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Picnic', 'Acao', 'Western Technologies', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Piece o Cake', 'Acao', 'Western Technologies', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Pizza Chef', 'Acao', 'Zimag', 'CCE', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Planet Patrol', 'Acao', 'Spectravision', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Pooyan', 'Acao', 'Konami', 'Konami', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Porkys', 'Aventura', 'Dunhill Electronic Media / Lazer Microsystems', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Q*berts Qubes', 'Acao', 'Mylstar Electronics', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Quest for Quintana Roo', 'Acao / Aventura', 'VSS', 'Sunrise', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Rabbit Transit', 'Acao', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Racing Car', 'Corrida', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Racquetball', 'Acao / Esporte', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Raft Rider', 'Acao', 'Western Technologies', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ram It', 'Acao', 'Telesys', 'Telesys', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Rampage', 'Acao', 'Bob Polaro', 'Activision', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Reactor', 'Acao', 'D. Gottlieb & Co.', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Red Sea Crossing', 'Acao', 'Steve Schustack', 'Inspirational Video Concepts', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Rescue Terra 1', 'Acao', 'VentureVision', 'VentureVision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Revenge of the Beefsteak Tomatoes', 'Acao', 'Fox Video Games', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('River Raid II', 'Acao', 'Imagineering', 'Activision', 1988, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Robin Hood', 'Acao', 'Xonox', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Roc n Rope', 'Acao', 'Coleco', 'Coleco', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Room of Doom', 'Acao', 'CommaVid', 'CommaVid', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Save Our Ship', 'Acao', 'Technovision', 'Technovision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Seahawk', 'Acao', 'Sancho / Tangs Electronic', 'Sancho / Tangs Electronic', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sea Monster', 'Acao', 'Bit Corporation', 'Bit Corporation', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Shootin Gallery', 'Acao', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Shuttle Orbiter', 'Acao / Simulacao', 'Avalon Hill', 'Avalon Hill', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sir Lancelot', 'Acao', 'Xonox', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Skate Boardin: A Radical Adventure', 'Acao / Esporte', 'Imagineering', 'Absolute Entertainment', 1988, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Skeet Shoot', 'Acao', 'Apollo', 'Apollo', 1981, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ski Hunt', 'Esporte', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Ski Run', 'Esporte', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Skindiver', 'Acao', 'Sancho / Tangs Electronic', 'Sancho / Tangs Electronic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sky Jinks', 'Corrida', 'Activision', 'Activision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sky Skipper', 'Acao', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Smurf: Rescue in Gargamels Castle', 'Acao', 'James Wickstead Design Associates', 'Coleco', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Smurfs Save the Day', 'Acao', 'Coleco', 'Coleco', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Snail Against Squirrel', 'Acao', 'Bit Corporation', 'Bit Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sneak N Peek', 'Simulacao', 'James Wickstead Design Associates', 'U.S. Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Solar Fox', 'Acao', 'CBS Electronics', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Solar Storm', 'Acao', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sorcerer', 'Acao', 'Mythicon', 'Mythicon', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Space Attack', 'Acao', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Space Cavern', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Space Tunnel', 'Acao', 'Bit Corporation', 'Bit Corporation', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spacechase', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Space Jockey', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Space Master X-7', 'Acao / Estrategia', 'Sirius Software', 'Fox Video Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spectracube Invasion', 'Acao', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spider-Man', 'Acao', 'Parker Brothers', 'Parker Brothers', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spikes Peak', 'Acao', 'Xonox', 'Xonox', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spitfire Attack', 'Acao', 'Milton Bradley', 'Milton Bradley', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Spy Hunter', 'Acao / Corrida', 'Sega', 'Sega', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Squeeze Box', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sssnake', 'Acao', 'Data Age', 'Data Age', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Fox', 'Acao', 'Mythicon', 'Mythicon', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Gunner', 'Acao', 'Telesys', 'Telesys', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Raiders II', 'Acao', 'Atari', 'Atari', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Strike', 'Acao', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Trek: Strategic Operations Simulator', 'Acao', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Wars: The Arcade Game', 'Acao', 'James Wickstead Design Associates', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Star Wars Return of the Jedi: Death Star Battle', 'Acao', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Stone Age', 'Acao', 'TechnoVision', 'CCE', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Strategy X', 'Acao', 'Konami', 'Konami', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Strawberry Shortcake: Musical Match-ups', 'Estrategia', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Stronghold', 'Acao', 'CommaVid', 'CommaVid', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sub-Scan', 'Estrategia', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Suicide Mission', 'Acao', 'Starpath', 'Starpath', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Summer Games', 'Esporte', 'Epyx', 'Epyx', 1987, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Super Challenge Baseball', 'Esporte', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Super Challenge Football', 'Esporte', 'APh Technological Consulting', 'M Network', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Super Cobra', 'Acao', 'Roklan Corporation', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Surfers Paradise: But Danger Below!', 'Acao / Esporte', 'Video Gems', 'Video Gems', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Survival Island', 'Aventura', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Survival Run', 'Acao', 'Renaissance Technology', 'Milton Bradley', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Sword of Saros', 'Aventura / RPG', 'Starpath', 'Starpath', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tac-Scan', 'Acao', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tapeworm', 'Acao', 'Spectravision', 'Spectravision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tapper', 'Acao', 'Beck-Tech', 'Sega', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tax Avoiders', 'Acao', 'Dunhill Electronics', 'American Videogame', 1986, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Threshold', 'Shooter', 'On-Line Systems', 'Tigervision', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Thunderground', 'Acao', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Time Pilot', 'Acao', 'Coleco', 'Coleco', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Time Warp', 'Acao', 'Funvision', 'Funvision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Title Match Pro Wrestling', 'Esporte', 'Imagineering', 'Absolute Entertainment', 1987, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tomarc the Barbarian', 'Acao', 'Xonox', 'Xonox', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tomcat: The F-14 Fighter Simulator', 'Acao / Simulacao', 'Imagineering', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tooth Protectors', 'Acao', 'DSD', 'Camelot', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Topy', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Towering Inferno', 'Acao', 'Western Technologies', 'U.S. Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Treasure Below', 'Acao', 'Video Gems', 'Video Gems', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Treasure Discovery', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Trick Shot', 'Esporte', 'Imagic', 'Imagic', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tron: Deadly Discs', 'Acao', 'APh Technological Consulting', 'M Network', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Tunnel Runner', 'Acao', 'CBS Electronics', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Turmoil', 'Acao', 'Sirius Software', 'Fox Video Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Universal Chaos', 'Acao', 'Telegames', 'Telegames', 1989, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Up n Down', 'Acao / Corrida', 'Sega', 'Sega', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Video Jogger', 'Acao', 'Exus Corporation', 'Exus Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Video Life', 'Simulacao', 'CommaVid', 'CommaVid', 1984, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Video Reflex', 'Acao', 'Exus Corporation', 'Exus Corporation', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Wabbit', 'Acao', 'Apollo', 'Apollo', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Walker', 'Acao', 'Suntek', 'Suntek', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Wall Ball', 'Acao', 'Avalon Hill', 'Avalon Hill', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Wall-Defender', 'Acao', 'Bomb', 'Bomb', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Warplock', 'Acao', 'Data Age', 'Data Age', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Wing War', 'Acao', 'Imagic', 'Imagic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Winter Games', 'Esporte', 'Action Graphics', 'Epyx', 1987, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Wizard of Wor', 'Acao', 'Roklan Corporation', 'CBS Electronics', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Word Zapper', 'Acao', 'James Wickstead Design Associates', 'U.S. Games', 1982, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('Words-Attack', 'Educacional', 'Home Vision', 'Sancho / Tangs Electronic', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('World End', 'Acao', 'Home Vision', 'Home Vision', 1983, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 2600.'),
('The Activision Decathlon', 'Esporte', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Astro Chase', 'Shooter', 'First Star Software', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Ballblazer', 'Esporte', 'Lucasfilm Games', 'Atari Corp.', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Beamrider', 'Shooter', 'Action Graphics', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Berzerk', 'Shooter', 'GCC', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Blue Print', 'Puzzle', 'Solitaire Group', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Bounty Bob Strikes Back!', 'Plataforma', 'Big Five Software', 'Big Five Software', 1985, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Buck Rogers: Planet of Zoom', 'Shooter', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Centipede', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Choplifter', 'Shooter', 'GCC', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Congo Bongo', 'Plataforma', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Countermeasure', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Defender', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Dig Dug', 'Arcade', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('The Dreadnaught Factor', 'Shooter', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Frogger', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Frogger II: ThreeeDeep!', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Galaxian', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Gorf', 'Shooter', 'Roklan Corporation', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Gremlins', 'Acao', 'Atari, Inc.', 'Atari Corp.', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Gyruss', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('H.E.R.O.', 'Acao', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('James Bond 007', 'Acao', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Joust', 'Arcade', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Jungle Hunt', 'Acao', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('K-Razy Shoot-Out', 'Shooter', 'K-Byte', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Kaboom!', 'Acao', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Kangaroo', 'Plataforma', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Keystone Kapers', 'Acao', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Mario Bros.', 'Plataforma', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Megamania', 'Shooter', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Meteorites', 'Shooter', 'Electra Concepts', 'Electra Concepts', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Miner 2049er', 'Plataforma', 'Big Five Software', 'Big Five Software', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Missile Command', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Montezuma''s Revenge', 'Plataforma', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Moon Patrol', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Mountain King', 'Plataforma', 'K-Byte', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Mr. Do''s Castle', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Ms. Pac-Man', 'Arcade', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Pac-Man', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Pengo', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Pitfall!', 'Plataforma', 'Beck-Tech', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Pitfall II: Lost Caverns', 'Plataforma', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Pole Position', 'Corrida', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Popeye', 'Plataforma', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Q*bert', 'Arcade', 'Parker Brothers', 'Parker Brothers', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Qix', 'Puzzle', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Quest for Quintana Roo', 'Aventura', 'VSS, Inc.', 'Sunrise Software', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('RealSports Baseball', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('RealSports Football', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('RealSports Soccer', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('RealSports Tennis', 'Esporte', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Rescue on Fractalus!', 'Shooter', 'Lucasfilm Games', 'Atari Corp.', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('River Raid', 'Shooter', 'Activision', 'Activision', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Robotron: 2084', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Space Dungeon', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Space Invaders', 'Shooter', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Space Shuttle: A Journey into Space', 'Simulador', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Star Raiders', 'Simulador', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Star Trek: Strategic Operations Simulator', 'Shooter', 'Sega', 'Sega', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Star Wars: Return of the Jedi Death Star Battle', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Star Wars: The Arcade Game', 'Shooter', 'Parker Brothers', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Super Breakout', 'Arcade', 'Atari, Inc.', 'Atari, Inc.', 1982, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Super Cobra', 'Shooter', 'Roklan Corporation', 'Parker Brothers', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Vanguard', 'Shooter', 'GCC', 'Atari, Inc.', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Wizard of Wor', 'Shooter', 'Roklan Corporation', 'CBS Electronics', 1983, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Zaxxon', 'Shooter', 'Sega', 'Sega', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Zenji', 'Puzzle', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('Zone Ranger', 'Shooter', 'Activision', 'Activision', 1984, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 5200.'),
('32 in 1', 'Compilacao', 'Atari Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Ace of Aces', 'Simulador', 'Nova Game Design', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Alien Brigade', 'Light gun', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Asteroids', 'Shooter', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Ballblazer', 'Esporte', 'General Computer Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Barnyard Blaster', 'Light gun', 'James Zalewski', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Basketbrawl', 'Esporte', 'BlueSky Software', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Centipede', 'Shooter', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Choplifter', 'Shooter', 'Ibid, Inc.', 'Atari Corporation', 1987, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Commando', 'Shooter', 'Sculptured Software', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Crack''ed', 'Puzzle', 'Robert Neve', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Crossbow', 'Light gun', 'Imagineering', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Dark Chambers', 'Dungeon crawl', 'Sculptured Software', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Desert Falcon', 'Shooter', 'General Computer Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Dig Dug', 'Arcade', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Donkey Kong', 'Plataforma', 'International Technology Development Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Donkey Kong Jr.', 'Plataforma', 'International Technology Development Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Double Dragon', 'Beat em up', 'Imagineering', 'Activision', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('F-18 Hornet', 'Simulador', 'Imagineering', 'Absolute Entertainment', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Fatal Run', 'Corrida', 'Sculptured Software', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Fight Night', 'Esporte', 'Imagineering', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Food Fight', 'Acao', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Galaga', 'Shooter', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Hat Trick', 'Esporte', 'Ibid, Inc.', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Ikari Warriors', 'Shooter', 'Imagineering', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Impossible Mission', 'Acao', 'Man Development Corp.', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Jinks', 'Acao', 'Softgold', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Joust', 'Arcade', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Karateka', 'Luta', 'Ibid, Inc.', 'Atari Corporation', 1987, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Kung-Fu Master', 'Beat em up', 'Imagineering', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Mario Bros.', 'Plataforma', 'International Technology Development Corporation', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Mat Mania Challenge', 'Esporte', 'BlueSky Software', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Mean 18 Ultimate Golf', 'Esporte', 'BlueSky Software', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Meltdown', 'Light gun', 'Atari Corporation', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Midnight Mutants', 'Acao', 'Radioactive Software', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Motor Psycho', 'Corrida', 'BlueSky Software', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Ms. Pac-Man', 'Arcade', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Ninja Golf', 'Acao', 'BlueSky Software', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('One-on-One Basketball', 'Esporte', 'Man Development Corp.', 'Atari Corporation', 1987, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Pete Rose Baseball', 'Esporte', 'Absolute Entertainment', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Planet Smashers', 'Shooter', 'Datafast Computer Services', 'Atari Corporation', 1990, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Pole Position II', 'Corrida', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Rampage', 'Acao', 'Activision', 'Activision', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('RealSports Baseball', 'Esporte', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Robotron: 2084', 'Shooter', 'General Computer Corporation', 'Atari Corporation', 1986, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Scrapyard Dog', 'Plataforma', 'BlueSky Software', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Sentinel', 'Light gun', 'Imagineering', 'Atari Corporation', 1991, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Summer Games', 'Esporte', 'Epyx', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Super Huey UH-IX', 'Simulador', 'Atari Corporation', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Super Skateboardin', 'Esporte', 'Absolute Entertainment', 'Absolute Entertainment', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Tank Command', 'Shooter', 'Froggo', 'Froggo', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Title Match Pro Wrestling', 'Esporte', 'Absolute Entertainment', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Tomcat: The F-14 Fighter Simulator', 'Simulador', 'Absolute Entertainment', 'Absolute Entertainment', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Touchdown Football', 'Esporte', 'Imagineering', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Tower Toppler', 'Plataforma', 'Hewson Consultants', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Water Ski', 'Esporte', 'Froggo', 'Froggo', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Winter Games', 'Esporte', 'Epyx', 'Atari Corporation', 1988, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Xenophobe', 'Acao', 'BlueSky Software', 'Atari Corporation', 1989, 'Sem classificacao', 'Single-player', 'Jogo lancado para Atari 7800.'),
('Bounty Bob Strikes Back', 'Plataforma', 'Atari', 'Atari', 2024, 'Sem classificacao', 'Single-player', 'Jogo comercial real lancado para Atari 7800.');