-- Seed de jogos de video games reais
-- Observacao: lista ampla/curada com jogos comerciais relevantes; nao representa literalmente todos os jogos ja criados.
-- Classificacao indicativa aproximada em padrao simples: Livre, 10, 12, 14, 16, 18.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO jogos (titulo, genero, desenvolvedora, publicadora, ano_lancamento, classificacao_indicativa, modo_jogo, descricao)
VALUES
('Pong', 'Esporte', 'Atari', 'Atari', 1972, 'Livre', 'Multiplayer', 'Jogo eletronico classico de tenis de mesa que ajudou a popularizar os arcades.'),
('Space Invaders', 'Tiro', 'Taito', 'Taito', 1978, 'Livre', 'Single-player', 'Arcade de tiro em tela fixa contra ondas de alienigenas.'),
('Asteroids', 'Tiro', 'Atari', 'Atari', 1979, 'Livre', 'Single-player', 'Arcade vetorial em que o jogador pilota uma nave e destrói asteroides.'),
('Pac-Man', 'Labirinto', 'Namco', 'Namco', 1980, 'Livre', 'Single-player', 'Classico arcade em que Pac-Man coleta pontos e foge de fantasmas em labirintos.'),
('Centipede', 'Tiro', 'Atari', 'Atari', 1981, 'Livre', 'Single-player', 'Arcade de tiro com criaturas segmentadas e controle por trackball.'),
('Donkey Kong', 'Plataforma', 'Nintendo R&D1', 'Nintendo', 1981, 'Livre', 'Single-player', 'Arcade de plataforma que apresentou Mario e Donkey Kong ao publico.'),
('Frogger', 'Acao', 'Konami', 'Sega', 1981, 'Livre', 'Single-player', 'Jogo em que o jogador guia um sapo por ruas e rios cheios de perigos.'),
('Galaga', 'Tiro', 'Namco', 'Namco', 1981, 'Livre', 'Single-player', 'Arcade de tiro espacial com formacoes inimigas e captura da nave do jogador.'),
('Ms. Pac-Man', 'Labirinto', 'General Computer Corporation', 'Midway', 1982, 'Livre', 'Single-player', 'Sequencia popular de Pac-Man com labirintos variados e comportamento de fantasmas ajustado.'),
('Dig Dug', 'Acao', 'Namco', 'Namco', 1982, 'Livre', 'Single-player', 'Arcade em que o jogador escava tuneis e derrota inimigos inflando-os ou usando pedras.'),
('Pole Position', 'Corrida', 'Namco', 'Atari', 1982, 'Livre', 'Single-player', 'Arcade de corrida em Formula 1 com perspectiva traseira e classificacao por tempo.'),
('Joust', 'Acao', 'Williams Electronics', 'Williams Electronics', 1982, 'Livre', 'Single-player e Multiplayer', 'Arcade de combate sobre aves voadoras em arenas de plataformas.'),
('Q*bert', 'Puzzle', 'Gottlieb', 'Gottlieb', 1982, 'Livre', 'Single-player', 'Puzzle arcade em que o personagem muda as cores de cubos em uma piramide isometrica.'),
('Dragon''s Lair', 'Aventura', 'Advanced Microcomputer Systems', 'Cinematronics', 1983, '10', 'Single-player', 'Jogo em laserdisc com animacao de Don Bluth e comandos por eventos.'),
('Mario Bros.', 'Plataforma', 'Nintendo R&D1', 'Nintendo', 1983, 'Livre', 'Single-player e Multiplayer', 'Arcade de plataforma em tela unica estrelado por Mario e Luigi.'),
('Tetris', 'Puzzle', 'Alexey Pajitnov', 'Various', 1984, 'Livre', 'Single-player', 'Puzzle de blocos criado na Uniao Sovietica e adaptado para diversas plataformas.'),
('Super Mario Bros.', 'Plataforma', 'Nintendo R&D4', 'Nintendo', 1985, 'Livre', 'Single-player e Multiplayer', 'Jogo de plataforma que consolidou Mario como mascote da Nintendo.'),
('Duck Hunt', 'Tiro', 'Nintendo R&D1', 'Nintendo', 1984, 'Livre', 'Single-player', 'Jogo de tiro com pistola de luz para NES baseado em cacar patos na tela.'),
('Excitebike', 'Corrida', 'Nintendo R&D1', 'Nintendo', 1984, 'Livre', 'Single-player', 'Jogo de motocross com pistas de obstaculos e editor de circuitos.'),
('Ice Climber', 'Plataforma', 'Nintendo R&D1', 'Nintendo', 1985, 'Livre', 'Single-player e Multiplayer', 'Plataforma vertical em que dois escaladores quebram blocos para subir montanhas.'),
('Ghosts ''n Goblins', 'Plataforma', 'Capcom', 'Capcom', 1985, '10', 'Single-player', 'Plataforma de acao conhecido por sua alta dificuldade e atmosfera medieval.'),
('Gauntlet', 'Acao RPG', 'Atari Games', 'Atari Games', 1985, '10', 'Single-player e Multiplayer', 'Arcade cooperativo com personagens de fantasia explorando masmorras.'),
('Gradius', 'Tiro', 'Konami', 'Konami', 1985, 'Livre', 'Single-player', 'Shoot ''em up lateral com sistema de power-ups e nave Vic Viper.'),
('The Legend of Zelda', 'Aventura', 'Nintendo R&D4', 'Nintendo', 1986, 'Livre', 'Single-player', 'Aventura de acao com exploracao aberta, masmorras e itens especiais.'),
('Metroid', 'Acao e Aventura', 'Nintendo R&D1', 'Nintendo', 1986, '10', 'Single-player', 'Jogo de exploracao nao linear estrelado pela cacadora de recompensas Samus Aran.'),
('Castlevania', 'Plataforma', 'Konami', 'Konami', 1986, '10', 'Single-player', 'Acao em plataforma em que Simon Belmont enfrenta Dracula e criaturas goticas.'),
('Kid Icarus', 'Plataforma', 'Nintendo R&D1', 'Nintendo', 1986, 'Livre', 'Single-player', 'Aventura de plataforma com Pit em um mundo inspirado na mitologia.'),
('Mega Man', 'Plataforma', 'Capcom', 'Capcom', 1987, 'Livre', 'Single-player', 'Plataforma de acao com selecao de fases e poderes obtidos de chefes.'),
('Contra', 'Run and Gun', 'Konami', 'Konami', 1987, '12', 'Single-player e Multiplayer', 'Jogo de tiro e plataforma com acao cooperativa intensa.'),
('Final Fantasy', 'RPG', 'Square', 'Square', 1987, '10', 'Single-player', 'RPG japones que deu inicio a uma das franquias mais importantes do genero.'),
('Metal Gear', 'Acao e Furtividade', 'Konami', 'Konami', 1987, '12', 'Single-player', 'Jogo de infiltracao criado por Hideo Kojima, precursor do genero stealth.'),
('Phantasy Star', 'RPG', 'Sega', 'Sega', 1987, '10', 'Single-player', 'RPG da Sega com ambientacao de ficcao cientifica e fantasia.'),
('Ninja Gaiden', 'Acao e Plataforma', 'Tecmo', 'Tecmo', 1988, '12', 'Single-player', 'Jogo de acao com ninjas, cenas cinematograficas e alta dificuldade.'),
('Super Mario Bros. 3', 'Plataforma', 'Nintendo R&D4', 'Nintendo', 1988, 'Livre', 'Single-player e Multiplayer', 'Um dos maiores classicos do NES, com mapa de mundo e novos poderes para Mario.'),
('Dragon Quest III', 'RPG', 'Chunsoft', 'Enix', 1988, '10', 'Single-player', 'RPG japones influente com sistema de classes e jornada heroica.'),
('Prince of Persia', 'Plataforma', 'Broderbund', 'Broderbund', 1989, '10', 'Single-player', 'Plataforma cinematografico conhecido por animacoes rotoscopadas.'),
('Teenage Mutant Ninja Turtles', 'Acao', 'Konami', 'Konami', 1989, '10', 'Single-player', 'Jogo de acao baseado nas Tartarugas Ninja com fases variadas.'),
('Sonic the Hedgehog', 'Plataforma', 'Sonic Team', 'Sega', 1991, 'Livre', 'Single-player', 'Plataforma veloz que apresentou Sonic como mascote da Sega.'),
('Street Fighter II', 'Luta', 'Capcom', 'Capcom', 1991, '12', 'Single-player e Multiplayer', 'Jogo de luta que popularizou combates competitivos com personagens diversos.'),
('The Legend of Zelda: A Link to the Past', 'Aventura', 'Nintendo EAD', 'Nintendo', 1991, 'Livre', 'Single-player', 'Aventura em Hyrule com mundo claro e mundo sombrio, itens e masmorras.'),
('Super Mario World', 'Plataforma', 'Nintendo EAD', 'Nintendo', 1990, 'Livre', 'Single-player e Multiplayer', 'Plataforma do Super Nintendo que apresentou Yoshi e expandiu a formula de Mario.'),
('F-Zero', 'Corrida', 'Nintendo EAD', 'Nintendo', 1990, 'Livre', 'Single-player', 'Corrida futurista em alta velocidade usando efeitos Mode 7 no Super Nintendo.'),
('ActRaiser', 'Acao e Simulacao', 'Quintet', 'Enix', 1990, '10', 'Single-player', 'Mistura fases de acao lateral com gerenciamento de civilizacao.'),
('Final Fantasy IV', 'RPG', 'Square', 'Square', 1991, '10', 'Single-player', 'RPG com narrativa dramatica e sistema Active Time Battle.'),
('Streets of Rage', 'Beat ''em Up', 'Sega', 'Sega', 1991, '12', 'Single-player e Multiplayer', 'Beat ''em up urbano da Sega com trilha sonora marcante.'),
('Mortal Kombat', 'Luta', 'Midway', 'Midway', 1992, '16', 'Single-player e Multiplayer', 'Jogo de luta famoso por digitalizacao de atores e golpes finais violentos.'),
('Sonic the Hedgehog 2', 'Plataforma', 'Sega Technical Institute', 'Sega', 1992, 'Livre', 'Single-player e Multiplayer', 'Sequencia de Sonic que introduziu Tails e ampliou a velocidade da serie.'),
('Super Mario Kart', 'Corrida', 'Nintendo EAD', 'Nintendo', 1992, 'Livre', 'Single-player e Multiplayer', 'Primeiro jogo da serie Mario Kart, com corridas e itens em pistas tematicas.'),
('Kirby''s Dream Land', 'Plataforma', 'HAL Laboratory', 'Nintendo', 1992, 'Livre', 'Single-player', 'Primeira aventura de Kirby, lancada para Game Boy.'),
('Wolfenstein 3D', 'Tiro em Primeira Pessoa', 'id Software', 'Apogee Software', 1992, '16', 'Single-player', 'FPS pioneiro que ajudou a definir a estrutura moderna do genero.'),
('Doom', 'Tiro em Primeira Pessoa', 'id Software', 'id Software', 1993, '16', 'Single-player e Multiplayer', 'FPS influente com acao rapida, demons e suporte a partidas em rede.'),
('Secret of Mana', 'RPG de Acao', 'Square', 'Square', 1993, '10', 'Single-player e Multiplayer', 'RPG de acao com combate em tempo real e modo cooperativo.'),
('Star Fox', 'Tiro', 'Nintendo EAD', 'Nintendo', 1993, 'Livre', 'Single-player', 'Jogo de nave com graficos poligonais usando o chip Super FX.'),
('Mega Man X', 'Acao e Plataforma', 'Capcom', 'Capcom', 1993, 'Livre', 'Single-player', 'Reinvencao da serie Mega Man no Super Nintendo com novo protagonista e mecanicas.'),
('Myst', 'Aventura', 'Cyan', 'Broderbund', 1993, 'Livre', 'Single-player', 'Aventura em primeira pessoa baseada em exploracao, enigmas e narrativa ambiental.'),
('Donkey Kong Country', 'Plataforma', 'Rare', 'Nintendo', 1994, 'Livre', 'Single-player e Multiplayer', 'Plataforma do SNES com graficos pre-renderizados e retorno de Donkey Kong.'),
('Final Fantasy VI', 'RPG', 'Square', 'Square', 1994, '10', 'Single-player', 'RPG aclamado por elenco amplo, narrativa madura e trilha sonora marcante.'),
('EarthBound', 'RPG', 'Ape / HAL Laboratory', 'Nintendo', 1994, '10', 'Single-player', 'RPG moderno e satirico ambientado em cidades e cenarios contemporaneos.'),
('Super Metroid', 'Acao e Aventura', 'Nintendo R&D1', 'Nintendo', 1994, '10', 'Single-player', 'Aventura de exploracao considerada referencia do estilo metroidvania.'),
('Sonic & Knuckles', 'Plataforma', 'Sega Technical Institute', 'Sega', 1994, 'Livre', 'Single-player', 'Jogo de plataforma com tecnologia lock-on para conectar cartuchos anteriores.'),
('Chrono Trigger', 'RPG', 'Square', 'Square', 1995, '10', 'Single-player', 'RPG japones com viagem no tempo, multiplos finais e equipe de criadores renomada.'),
('Yoshi''s Island', 'Plataforma', 'Nintendo EAD', 'Nintendo', 1995, 'Livre', 'Single-player', 'Plataforma estrelado por Yoshi com visual desenhado a mao.'),
('Command & Conquer', 'Estrategia em Tempo Real', 'Westwood Studios', 'Virgin Interactive', 1995, '12', 'Single-player e Multiplayer', 'RTS influente com construcao de bases, coleta de recursos e campanhas distintas.'),
('Warcraft II: Tides of Darkness', 'Estrategia em Tempo Real', 'Blizzard Entertainment', 'Blizzard Entertainment', 1995, '12', 'Single-player e Multiplayer', 'RTS de fantasia com conflito entre humanos e orcs.'),
('Resident Evil', 'Survival Horror', 'Capcom', 'Capcom', 1996, '16', 'Single-player', 'Survival horror com exploracao de mansao, zumbis e recursos limitados.'),
('Super Mario 64', 'Plataforma', 'Nintendo EAD', 'Nintendo', 1996, 'Livre', 'Single-player', 'Marco dos jogos 3D com exploracao livre em mundos conectados pelo castelo.'),
('Crash Bandicoot', 'Plataforma', 'Naughty Dog', 'Sony Computer Entertainment', 1996, 'Livre', 'Single-player', 'Plataforma 3D estrelado por Crash em fases lineares e cheias de obstaculos.'),
('Tomb Raider', 'Acao e Aventura', 'Core Design', 'Eidos Interactive', 1996, '12', 'Single-player', 'Aventura 3D com Lara Croft, exploracao, plataformas e ruinas antigas.'),
('Quake', 'Tiro em Primeira Pessoa', 'id Software', 'GT Interactive', 1996, '16', 'Single-player e Multiplayer', 'FPS totalmente 3D com forte foco em multiplayer e modificacoes.'),
('Diablo', 'RPG de Acao', 'Blizzard North', 'Blizzard Entertainment', 1996, '14', 'Single-player e Multiplayer', 'RPG de acao com masmorras geradas proceduralmente e loot.'),
('Pokemon Red', 'RPG', 'Game Freak', 'Nintendo', 1996, 'Livre', 'Single-player e Multiplayer', 'RPG de colecionar, treinar e batalhar criaturas Pokemon.'),
('Pokemon Blue', 'RPG', 'Game Freak', 'Nintendo', 1996, 'Livre', 'Single-player e Multiplayer', 'Versao complementar de Pokemon Red com criaturas exclusivas.'),
('Mario Kart 64', 'Corrida', 'Nintendo EAD', 'Nintendo', 1996, 'Livre', 'Single-player e Multiplayer', 'Corrida de kart em 3D com itens e multiplayer local para ate quatro jogadores.'),
('Final Fantasy VII', 'RPG', 'Square', 'Sony Computer Entertainment', 1997, '12', 'Single-player', 'RPG que popularizou a serie Final Fantasy no ocidente com graficos 3D e cenas CG.'),
('Castlevania: Symphony of the Night', 'Acao e Aventura', 'Konami', 'Konami', 1997, '10', 'Single-player', 'Metroidvania com exploracao de castelo, progressao RPG e protagonista Alucard.'),
('GoldenEye 007', 'Tiro em Primeira Pessoa', 'Rare', 'Nintendo', 1997, '12', 'Single-player e Multiplayer', 'FPS do Nintendo 64 baseado no filme de James Bond, famoso pelo multiplayer local.'),
('Gran Turismo', 'Corrida', 'Polyphony Digital', 'Sony Computer Entertainment', 1997, 'Livre', 'Single-player e Multiplayer', 'Simulador de corrida com grande variedade de carros e licencas.'),
('Fallout', 'RPG', 'Interplay Productions', 'Interplay Productions', 1997, '16', 'Single-player', 'RPG pos-apocaliptico com escolhas morais, combate por turnos e mundo aberto isometrico.'),
('Star Fox 64', 'Tiro', 'Nintendo EAD', 'Nintendo', 1997, 'Livre', 'Single-player', 'Jogo de nave em trilhos com dublagem, rotas alternativas e Rumble Pak.'),
('Age of Empires', 'Estrategia em Tempo Real', 'Ensemble Studios', 'Microsoft', 1997, '12', 'Single-player e Multiplayer', 'RTS historico com civilizacoes antigas, coleta de recursos e evolucao tecnologica.'),
('The Legend of Zelda: Ocarina of Time', 'Aventura', 'Nintendo EAD', 'Nintendo', 1998, 'Livre', 'Single-player', 'Aventura 3D considerada marco do genero, com viagem no tempo e masmorras.'),
('Metal Gear Solid', 'Acao e Furtividade', 'Konami Computer Entertainment Japan', 'Konami', 1998, '14', 'Single-player', 'Jogo de infiltracao cinematografico estrelado por Solid Snake.'),
('Resident Evil 2', 'Survival Horror', 'Capcom', 'Capcom', 1998, '16', 'Single-player', 'Sequencia ambientada em Raccoon City com campanhas conectadas.'),
('Half-Life', 'Tiro em Primeira Pessoa', 'Valve', 'Sierra Studios', 1998, '16', 'Single-player', 'FPS narrativo que integrou historia e acao sem cortes cinematograficos tradicionais.'),
('StarCraft', 'Estrategia em Tempo Real', 'Blizzard Entertainment', 'Blizzard Entertainment', 1998, '12', 'Single-player e Multiplayer', 'RTS de ficcao cientifica com tres faccoes assimetricas.'),
('Banjo-Kazooie', 'Plataforma', 'Rare', 'Nintendo', 1998, 'Livre', 'Single-player', 'Plataforma 3D com exploracao, colecionaveis e humor.'),
('Spyro the Dragon', 'Plataforma', 'Insomniac Games', 'Sony Computer Entertainment', 1998, 'Livre', 'Single-player', 'Plataforma 3D estrelado por um dragao roxo em mundos abertos.'),
('Pokemon Yellow', 'RPG', 'Game Freak', 'Nintendo', 1998, 'Livre', 'Single-player e Multiplayer', 'Versao especial inspirada no anime Pokemon com Pikachu acompanhando o jogador.'),
('Silent Hill', 'Survival Horror', 'Team Silent', 'Konami', 1999, '16', 'Single-player', 'Terror psicologico com atmosfera sombria, neblina e narrativa simbolica.'),
('Tony Hawk''s Pro Skater', 'Esporte', 'Neversoft', 'Activision', 1999, 'Livre', 'Single-player e Multiplayer', 'Jogo de skate arcade com manobras, combos e trilha sonora marcante.'),
('Super Smash Bros.', 'Luta', 'HAL Laboratory', 'Nintendo', 1999, 'Livre', 'Single-player e Multiplayer', 'Jogo de luta crossover da Nintendo com arenas e mecanicas de expulsao.'),
('Shenmue', 'Aventura', 'Sega AM2', 'Sega', 1999, '12', 'Single-player', 'Aventura cinematografica em mundo aberto com elementos de simulacao e investigacao.'),
('Age of Empires II: The Age of Kings', 'Estrategia em Tempo Real', 'Ensemble Studios', 'Microsoft', 1999, '12', 'Single-player e Multiplayer', 'RTS medieval com campanhas historicas e civilizacoes variadas.'),
('System Shock 2', 'RPG de Acao', 'Irrational Games / Looking Glass Studios', 'Electronic Arts', 1999, '16', 'Single-player', 'RPG imersivo de terror e ficcao cientifica em uma nave espacial.'),
('The Sims', 'Simulacao', 'Maxis', 'Electronic Arts', 2000, '12', 'Single-player', 'Simulador de vida em que o jogador controla rotinas, casas e relacionamentos.'),
('Diablo II', 'RPG de Acao', 'Blizzard North', 'Blizzard Entertainment', 2000, '16', 'Single-player e Multiplayer', 'RPG de acao com classes, atos, loot e forte comunidade online.'),
('Counter-Strike', 'Tiro em Primeira Pessoa', 'Valve', 'Sierra Studios', 2000, '16', 'Multiplayer', 'FPS competitivo entre terroristas e contra-terroristas, originado de mod de Half-Life.'),
('Deus Ex', 'RPG de Acao', 'Ion Storm', 'Eidos Interactive', 2000, '16', 'Single-player', 'RPG imersivo com escolhas, conspiracoes e multiplas abordagens de missao.'),
('Perfect Dark', 'Tiro em Primeira Pessoa', 'Rare', 'Nintendo', 2000, '16', 'Single-player e Multiplayer', 'FPS do Nintendo 64 com campanha futurista e multiplayer robusto.'),
('Final Fantasy IX', 'RPG', 'Square', 'Square', 2000, '10', 'Single-player', 'RPG que retorna a elementos de fantasia classica da franquia Final Fantasy.'),
('Majora''s Mask', 'Aventura', 'Nintendo EAD', 'Nintendo', 2000, '10', 'Single-player', 'Aventura de Zelda com ciclo temporal de tres dias e atmosfera sombria.'),
('Baldur''s Gate II: Shadows of Amn', 'RPG', 'BioWare', 'Interplay Entertainment', 2000, '12', 'Single-player e Multiplayer', 'RPG baseado em Dungeons & Dragons com narrativa extensa e combate tatico.'),
('Gran Turismo 3: A-Spec', 'Corrida', 'Polyphony Digital', 'Sony Computer Entertainment', 2001, 'Livre', 'Single-player e Multiplayer', 'Simulador de corrida para PlayStation 2 com graficos avancados para a epoca.'),
('Halo: Combat Evolved', 'Tiro em Primeira Pessoa', 'Bungie', 'Microsoft Game Studios', 2001, '16', 'Single-player e Multiplayer', 'FPS que consolidou o Xbox, estrelado por Master Chief.'),
('Grand Theft Auto III', 'Acao e Aventura', 'DMA Design', 'Rockstar Games', 2001, '18', 'Single-player', 'Jogo de mundo aberto urbano em 3D ambientado em Liberty City.'),
('Super Smash Bros. Melee', 'Luta', 'HAL Laboratory', 'Nintendo', 2001, 'Livre', 'Single-player e Multiplayer', 'Sequencia de Smash Bros. com jogabilidade rapida e forte cena competitiva.'),
('Metal Gear Solid 2: Sons of Liberty', 'Acao e Furtividade', 'Konami Computer Entertainment Japan', 'Konami', 2001, '16', 'Single-player', 'Sequencia cinematografica com temas de informacao, controle e identidade.'),
('Silent Hill 2', 'Survival Horror', 'Team Silent', 'Konami', 2001, '16', 'Single-player', 'Terror psicologico focado em culpa, trauma e simbolismo.'),
('Devil May Cry', 'Acao', 'Capcom Production Studio 4', 'Capcom', 2001, '16', 'Single-player', 'Jogo de acao estilosa com Dante enfrentando demonios.'),
('Pikmin', 'Estrategia', 'Nintendo EAD', 'Nintendo', 2001, 'Livre', 'Single-player', 'Jogo de estrategia e exploracao com criaturas Pikmin em um planeta desconhecido.'),
('Kingdom Hearts', 'RPG de Acao', 'Square', 'Square', 2002, '10', 'Single-player', 'RPG de acao que mistura personagens da Disney e Final Fantasy.'),
('Metroid Prime', 'Acao e Aventura', 'Retro Studios', 'Nintendo', 2002, '12', 'Single-player', 'Transposicao de Metroid para primeira pessoa com exploracao e combate.'),
('The Elder Scrolls III: Morrowind', 'RPG', 'Bethesda Game Studios', 'Bethesda Softworks', 2002, '16', 'Single-player', 'RPG de mundo aberto em Vvardenfell com grande liberdade de exploracao.'),
('Battlefield 1942', 'Tiro em Primeira Pessoa', 'DICE', 'Electronic Arts', 2002, '16', 'Single-player e Multiplayer', 'FPS de guerra com veiculos, classes e batalhas multiplayer amplas.'),
('Grand Theft Auto: Vice City', 'Acao e Aventura', 'Rockstar North', 'Rockstar Games', 2002, '18', 'Single-player', 'Mundo aberto inspirado nos anos 1980, ambientado em Vice City.'),
('Animal Crossing', 'Simulacao', 'Nintendo EAD', 'Nintendo', 2001, 'Livre', 'Single-player', 'Simulador social em tempo real com vila, vizinhos animais e colecionaveis.'),
('Ratchet & Clank', 'Plataforma', 'Insomniac Games', 'Sony Computer Entertainment', 2002, '10', 'Single-player', 'Plataforma e tiro com dupla de herois em aventura espacial.'),
('Sly Cooper and the Thievius Raccoonus', 'Plataforma', 'Sucker Punch Productions', 'Sony Computer Entertainment', 2002, 'Livre', 'Single-player', 'Plataforma de furtividade com estilo cartunesco e roubos.'),
('The Legend of Zelda: The Wind Waker', 'Aventura', 'Nintendo EAD', 'Nintendo', 2002, 'Livre', 'Single-player', 'Aventura em mar aberto com visual cel-shading e exploracao naval.'),
('Prince of Persia: The Sands of Time', 'Acao e Aventura', 'Ubisoft Montreal', 'Ubisoft', 2003, '12', 'Single-player', 'Aventura com parkour, combate e mecanica de rebobinar o tempo.'),
('Star Wars: Knights of the Old Republic', 'RPG', 'BioWare', 'LucasArts', 2003, '12', 'Single-player', 'RPG baseado em Star Wars com escolhas morais e combate tatico.'),
('Call of Duty', 'Tiro em Primeira Pessoa', 'Infinity Ward', 'Activision', 2003, '16', 'Single-player e Multiplayer', 'FPS de Segunda Guerra Mundial com campanhas cinematograficas.'),
('Max Payne 2: The Fall of Max Payne', 'Tiro em Terceira Pessoa', 'Remedy Entertainment', 'Rockstar Games', 2003, '16', 'Single-player', 'Jogo de acao noir com bullet time e narrativa sombria.'),
('Beyond Good & Evil', 'Acao e Aventura', 'Ubisoft Montpellier', 'Ubisoft', 2003, '12', 'Single-player', 'Aventura com investigacao, fotografia, combate e critica politica.'),
('Need for Speed: Underground', 'Corrida', 'EA Black Box', 'Electronic Arts', 2003, 'Livre', 'Single-player e Multiplayer', 'Corrida urbana focada em tuning, cultura de rua e provas noturnas.'),
('Mario Kart: Double Dash!!', 'Corrida', 'Nintendo EAD', 'Nintendo', 2003, 'Livre', 'Single-player e Multiplayer', 'Mario Kart do GameCube com dois personagens por kart.'),
('World of Warcraft', 'MMORPG', 'Blizzard Entertainment', 'Blizzard Entertainment', 2004, '12', 'Online Multiplayer', 'MMORPG ambientado em Azeroth, com missoes, masmorras, raids e faccoes.'),
('Half-Life 2', 'Tiro em Primeira Pessoa', 'Valve', 'Valve', 2004, '16', 'Single-player', 'FPS narrativo com fisica avancada e retorno de Gordon Freeman.'),
('Grand Theft Auto: San Andreas', 'Acao e Aventura', 'Rockstar North', 'Rockstar Games', 2004, '18', 'Single-player', 'Mundo aberto ambientado no estado ficticio de San Andreas nos anos 1990.'),
('Halo 2', 'Tiro em Primeira Pessoa', 'Bungie', 'Microsoft Game Studios', 2004, '16', 'Single-player e Multiplayer', 'Sequencia de Halo com forte foco no multiplayer online via Xbox Live.'),
('Metal Gear Solid 3: Snake Eater', 'Acao e Furtividade', 'Konami Computer Entertainment Japan', 'Konami', 2004, '16', 'Single-player', 'Prequela ambientada na Guerra Fria, com sobrevivencia na selva e espionagem.'),
('Fable', 'RPG de Acao', 'Lionhead Studios', 'Microsoft Game Studios', 2004, '16', 'Single-player', 'RPG de acao com escolhas morais e evolucao visual do personagem.'),
('Far Cry', 'Tiro em Primeira Pessoa', 'Crytek', 'Ubisoft', 2004, '16', 'Single-player e Multiplayer', 'FPS em ilhas tropicais com mapas abertos e IA avancada para a epoca.'),
('Katamari Damacy', 'Puzzle e Acao', 'Namco', 'Namco', 2004, 'Livre', 'Single-player', 'Jogo peculiar em que o jogador rola uma bola adesiva para coletar objetos.'),
('Resident Evil 4', 'Survival Horror', 'Capcom Production Studio 4', 'Capcom', 2005, '18', 'Single-player', 'Reinvencao da serie com camera sobre o ombro e foco maior em acao.'),
('God of War', 'Acao e Aventura', 'Santa Monica Studio', 'Sony Computer Entertainment', 2005, '18', 'Single-player', 'Acao mitologica estrelada por Kratos em sua busca contra os deuses gregos.'),
('Shadow of the Colossus', 'Acao e Aventura', 'Team Ico', 'Sony Computer Entertainment', 2005, '12', 'Single-player', 'Aventura minimalista focada em derrotar colossos gigantes em um mundo desolado.'),
('Guitar Hero', 'Ritmo', 'Harmonix', 'RedOctane', 2005, 'Livre', 'Single-player e Multiplayer', 'Jogo musical com controle em formato de guitarra e faixas de rock.'),
('Forza Motorsport', 'Corrida', 'Turn 10 Studios', 'Microsoft Game Studios', 2005, 'Livre', 'Single-player e Multiplayer', 'Simulador de corrida da Microsoft com carros licenciados e ajustes de desempenho.'),
('Psychonauts', 'Plataforma', 'Double Fine Productions', 'Majesco Entertainment', 2005, '10', 'Single-player', 'Plataforma criativo sobre poderes psiquicos e mundos mentais.'),
('Okami', 'Acao e Aventura', 'Clover Studio', 'Capcom', 2006, '10', 'Single-player', 'Aventura com visual inspirado em pintura japonesa e mecanica de pincel celestial.'),
('The Elder Scrolls IV: Oblivion', 'RPG', 'Bethesda Game Studios', 'Bethesda Softworks', 2006, '16', 'Single-player', 'RPG de mundo aberto ambientado em Cyrodiil, com portais de Oblivion.'),
('Gears of War', 'Tiro em Terceira Pessoa', 'Epic Games', 'Microsoft Game Studios', 2006, '18', 'Single-player e Multiplayer', 'Jogo de tiro em cobertura que popularizou mecanicas modernas do genero.'),
('Wii Sports', 'Esporte', 'Nintendo EAD', 'Nintendo', 2006, 'Livre', 'Single-player e Multiplayer', 'Colecao de esportes com controles por movimento, inclusa com o Nintendo Wii em varios mercados.'),
('New Super Mario Bros.', 'Plataforma', 'Nintendo EAD', 'Nintendo', 2006, 'Livre', 'Single-player', 'Retorno de Mario ao estilo de plataforma lateral no Nintendo DS.'),
('The Legend of Zelda: Twilight Princess', 'Aventura', 'Nintendo EAD', 'Nintendo', 2006, '12', 'Single-player', 'Aventura de Zelda com tom mais sombrio e transformacao de Link em lobo.'),
('BioShock', 'Tiro em Primeira Pessoa', '2K Boston / 2K Australia', '2K Games', 2007, '18', 'Single-player', 'FPS narrativo ambientado na cidade submersa de Rapture.'),
('Mass Effect', 'RPG de Acao', 'BioWare', 'Microsoft Game Studios', 2007, '16', 'Single-player', 'RPG de ficcao cientifica com escolhas narrativas e exploracao espacial.'),
('Assassin''s Creed', 'Acao e Aventura', 'Ubisoft Montreal', 'Ubisoft', 2007, '16', 'Single-player', 'Aventura historica com parkour, furtividade e conflito entre Assassinos e Templarios.'),
('Portal', 'Puzzle', 'Valve', 'Valve', 2007, '10', 'Single-player', 'Puzzle em primeira pessoa com portais e humor conduzido por GLaDOS.'),
('Call of Duty 4: Modern Warfare', 'Tiro em Primeira Pessoa', 'Infinity Ward', 'Activision', 2007, '16', 'Single-player e Multiplayer', 'FPS militar moderno que redefiniu a serie Call of Duty.'),
('Super Mario Galaxy', 'Plataforma', 'Nintendo EAD Tokyo', 'Nintendo', 2007, 'Livre', 'Single-player', 'Plataforma 3D com gravidade planetaria e fases espaciais.'),
('Uncharted: Drake''s Fortune', 'Acao e Aventura', 'Naughty Dog', 'Sony Computer Entertainment', 2007, '14', 'Single-player', 'Aventura cinematografica estrelada por Nathan Drake.'),
('Crysis', 'Tiro em Primeira Pessoa', 'Crytek', 'Electronic Arts', 2007, '16', 'Single-player e Multiplayer', 'FPS famoso por graficos avancados e tecnologia CryEngine.'),
('Rock Band', 'Ritmo', 'Harmonix', 'MTV Games', 2007, '12', 'Single-player e Multiplayer', 'Jogo musical em banda com guitarra, baixo, bateria e vocal.'),
('Fallout 3', 'RPG de Acao', 'Bethesda Game Studios', 'Bethesda Softworks', 2008, '18', 'Single-player', 'RPG pos-apocaliptico em mundo aberto na Capital Wasteland.'),
('Grand Theft Auto IV', 'Acao e Aventura', 'Rockstar North', 'Rockstar Games', 2008, '18', 'Single-player e Multiplayer', 'Mundo aberto em Liberty City com narrativa centrada em Niko Bellic.'),
('Metal Gear Solid 4: Guns of the Patriots', 'Acao e Furtividade', 'Kojima Productions', 'Konami', 2008, '16', 'Single-player', 'Conclusao da historia de Solid Snake com narrativa cinematografica extensa.'),
('Left 4 Dead', 'Tiro em Primeira Pessoa', 'Valve South', 'Valve', 2008, '18', 'Single-player e Multiplayer', 'FPS cooperativo contra hordas de infectados com IA dinamica.'),
('Dead Space', 'Survival Horror', 'EA Redwood Shores', 'Electronic Arts', 2008, '18', 'Single-player', 'Terror espacial com desmembramento estrategico e atmosfera claustrofobica.'),
('LittleBigPlanet', 'Plataforma', 'Media Molecule', 'Sony Computer Entertainment', 2008, 'Livre', 'Single-player e Multiplayer', 'Plataforma com forte foco em criacao e compartilhamento de fases.'),
('Mario Kart Wii', 'Corrida', 'Nintendo EAD', 'Nintendo', 2008, 'Livre', 'Single-player e Multiplayer', 'Mario Kart para Wii com controles por movimento e corridas online.'),
('Demon''s Souls', 'RPG de Acao', 'FromSoftware', 'Sony Computer Entertainment', 2009, '16', 'Single-player e Online', 'RPG de acao desafiador que estabeleceu as bases da serie Souls.'),
('Batman: Arkham Asylum', 'Acao e Aventura', 'Rocksteady Studios', 'Eidos Interactive', 2009, '14', 'Single-player', 'Aventura de Batman com combate fluido, furtividade e investigacao.'),
('Minecraft', 'Sandbox', 'Mojang Studios', 'Mojang Studios', 2011, 'Livre', 'Single-player e Multiplayer', 'Jogo sandbox de construcao, sobrevivencia e exploracao em mundo procedural.'),
('Borderlands', 'Tiro e RPG', 'Gearbox Software', '2K Games', 2009, '18', 'Single-player e Multiplayer', 'Loot shooter com visual cel-shading e cooperativo.'),
('Dragon Age: Origins', 'RPG', 'BioWare', 'Electronic Arts', 2009, '16', 'Single-player', 'RPG de fantasia sombria com escolhas narrativas e combate em grupo.'),
('Plants vs. Zombies', 'Tower Defense', 'PopCap Games', 'PopCap Games', 2009, 'Livre', 'Single-player', 'Defesa de torres casual em que plantas enfrentam zumbis.'),
('Call of Duty: Modern Warfare 2', 'Tiro em Primeira Pessoa', 'Infinity Ward', 'Activision', 2009, '18', 'Single-player e Multiplayer', 'Sequencia de Modern Warfare com campanha cinematografica e multiplayer popular.'),
('League of Legends', 'MOBA', 'Riot Games', 'Riot Games', 2009, '12', 'Online Multiplayer', 'MOBA competitivo em equipes, com campeoes e estrategia em arena.'),
('Mass Effect 2', 'RPG de Acao', 'BioWare', 'Electronic Arts', 2010, '16', 'Single-player', 'RPG de ficcao cientifica focado em personagens, escolhas e missao suicida.'),
('Red Dead Redemption', 'Acao e Aventura', 'Rockstar San Diego', 'Rockstar Games', 2010, '18', 'Single-player e Multiplayer', 'Mundo aberto de faroeste estrelado por John Marston.'),
('God of War III', 'Acao e Aventura', 'Santa Monica Studio', 'Sony Computer Entertainment', 2010, '18', 'Single-player', 'Conclusao da trilogia grega de Kratos contra o Olimpo.'),
('Super Mario Galaxy 2', 'Plataforma', 'Nintendo EAD Tokyo', 'Nintendo', 2010, 'Livre', 'Single-player', 'Sequencia de Super Mario Galaxy com novas ideias de gravidade e Yoshi.'),
('StarCraft II: Wings of Liberty', 'Estrategia em Tempo Real', 'Blizzard Entertainment', 'Blizzard Entertainment', 2010, '12', 'Single-player e Multiplayer', 'RTS competitivo e campanha focada nos Terranos.'),
('Alan Wake', 'Acao e Suspense', 'Remedy Entertainment', 'Microsoft Game Studios', 2010, '16', 'Single-player', 'Thriller psicologico sobre um escritor enfrentando criaturas da escuridao.'),
('Limbo', 'Puzzle e Plataforma', 'Playdead', 'Playdead', 2010, '16', 'Single-player', 'Puzzle-plataforma minimalista com estetica sombria em preto e branco.'),
('Super Meat Boy', 'Plataforma', 'Team Meat', 'Team Meat', 2010, '12', 'Single-player', 'Plataforma indie de alta precisao e dificuldade elevada.'),
('The Elder Scrolls V: Skyrim', 'RPG', 'Bethesda Game Studios', 'Bethesda Softworks', 2011, '16', 'Single-player', 'RPG de mundo aberto em Skyrim com dragoes, guildas e grande liberdade.'),
('Dark Souls', 'RPG de Acao', 'FromSoftware', 'Namco Bandai Games', 2011, '16', 'Single-player e Online', 'RPG de acao desafiador com mundo interconectado e combate punitivo.'),
('Portal 2', 'Puzzle', 'Valve', 'Valve', 2011, '10', 'Single-player e Multiplayer', 'Puzzle em primeira pessoa com portais, modo cooperativo e narrativa com humor.'),
('Uncharted 3: Drake''s Deception', 'Acao e Aventura', 'Naughty Dog', 'Sony Computer Entertainment', 2011, '14', 'Single-player e Multiplayer', 'Aventura cinematografica de Nathan Drake com grandes sequencias de acao.'),
('The Legend of Zelda: Skyward Sword', 'Aventura', 'Nintendo EAD', 'Nintendo', 2011, '10', 'Single-player', 'Aventura de Zelda para Wii com controles de movimento precisos.'),
('Batman: Arkham City', 'Acao e Aventura', 'Rocksteady Studios', 'Warner Bros. Interactive Entertainment', 2011, '14', 'Single-player', 'Sequencia de Arkham Asylum em uma area aberta de Gotham.'),
('Terraria', 'Sandbox', 'Re-Logic', 'Re-Logic', 2011, '10', 'Single-player e Multiplayer', 'Sandbox 2D com mineracao, construcao, exploracao e chefes.'),
('The Walking Dead', 'Aventura', 'Telltale Games', 'Telltale Games', 2012, '16', 'Single-player', 'Aventura narrativa baseada em escolhas em um mundo dominado por zumbis.'),
('Journey', 'Aventura', 'Thatgamecompany', 'Sony Computer Entertainment', 2012, 'Livre', 'Single-player e Online', 'Aventura poetica no deserto com comunicacao minimalista entre jogadores.'),
('Dishonored', 'Acao e Furtividade', 'Arkane Studios', 'Bethesda Softworks', 2012, '18', 'Single-player', 'Imersive sim com poderes sobrenaturais, furtividade e escolhas de abordagem.'),
('Far Cry 3', 'Tiro em Primeira Pessoa', 'Ubisoft Montreal', 'Ubisoft', 2012, '18', 'Single-player e Multiplayer', 'FPS de mundo aberto em ilha tropical com vilao marcante.'),
('XCOM: Enemy Unknown', 'Estrategia Tatica', 'Firaxis Games', '2K Games', 2012, '16', 'Single-player e Multiplayer', 'Estrategia tatica por turnos contra invasao alienigena.'),
('Borderlands 2', 'Tiro e RPG', 'Gearbox Software', '2K Games', 2012, '18', 'Single-player e Multiplayer', 'Loot shooter cooperativo com humor e grande variedade de armas.'),
('Hotline Miami', 'Acao', 'Dennaton Games', 'Devolver Digital', 2012, '18', 'Single-player', 'Acao top-down violenta com ritmo rapido, estetica neon e trilha marcante.'),
('The Last of Us', 'Acao e Aventura', 'Naughty Dog', 'Sony Computer Entertainment', 2013, '18', 'Single-player e Multiplayer', 'Drama pos-apocaliptico sobre Joel e Ellie em uma jornada pelos EUA.'),
('Grand Theft Auto V', 'Acao e Aventura', 'Rockstar North', 'Rockstar Games', 2013, '18', 'Single-player e Online', 'Mundo aberto em Los Santos com tres protagonistas e modo GTA Online.'),
('BioShock Infinite', 'Tiro em Primeira Pessoa', 'Irrational Games', '2K Games', 2013, '18', 'Single-player', 'FPS narrativo ambientado na cidade flutuante de Columbia.'),
('Tomb Raider', 'Acao e Aventura', 'Crystal Dynamics', 'Square Enix', 2013, '16', 'Single-player e Multiplayer', 'Reinicio da serie mostrando a origem de Lara Croft.'),
('Assassin''s Creed IV: Black Flag', 'Acao e Aventura', 'Ubisoft Montreal', 'Ubisoft', 2013, '16', 'Single-player e Multiplayer', 'Aventura pirata em mundo aberto com exploracao naval.'),
('Dota 2', 'MOBA', 'Valve', 'Valve', 2013, '12', 'Online Multiplayer', 'MOBA competitivo baseado no mod Defense of the Ancients.'),
('The Stanley Parable', 'Aventura', 'Galactic Cafe', 'Galactic Cafe', 2013, '12', 'Single-player', 'Jogo narrativo metalinguistico sobre escolhas, obediencia e narrador.'),
('Papers, Please', 'Simulacao', 'Lucas Pope', '3909 LLC', 2013, '14', 'Single-player', 'Simulador de fiscal de imigração em um estado ficticio autoritario.'),
('Gone Home', 'Aventura', 'The Fullbright Company', 'The Fullbright Company', 2013, '14', 'Single-player', 'Exploracao narrativa em primeira pessoa dentro de uma casa vazia.'),
('Destiny', 'Tiro em Primeira Pessoa', 'Bungie', 'Activision', 2014, '14', 'Online Multiplayer', 'FPS online com elementos de RPG, missoes cooperativas e raids.'),
('Dark Souls II', 'RPG de Acao', 'FromSoftware', 'Bandai Namco Games', 2014, '16', 'Single-player e Online', 'Sequencia de Dark Souls com novos reinos, inimigos e sistemas.'),
('Mario Kart 8', 'Corrida', 'Nintendo EAD', 'Nintendo', 2014, 'Livre', 'Single-player e Multiplayer', 'Mario Kart com pistas antigravidade e corridas online.'),
('Dragon Age: Inquisition', 'RPG', 'BioWare', 'Electronic Arts', 2014, '16', 'Single-player e Multiplayer', 'RPG de fantasia com grandes areas abertas e comando da Inquisicao.'),
('Alien: Isolation', 'Survival Horror', 'Creative Assembly', 'Sega', 2014, '16', 'Single-player', 'Terror de sobrevivencia inspirado no filme Alien, com xenomorfo perseguindo o jogador.'),
('Middle-earth: Shadow of Mordor', 'Acao e Aventura', 'Monolith Productions', 'Warner Bros. Interactive Entertainment', 2014, '16', 'Single-player', 'Aventura em Mordor com sistema Nemesis de inimigos dinamicos.'),
('Hearthstone', 'Cartas', 'Blizzard Entertainment', 'Blizzard Entertainment', 2014, 'Livre', 'Single-player e Multiplayer', 'Jogo digital de cartas baseado no universo Warcraft.'),
('The Witcher 3: Wild Hunt', 'RPG de Acao', 'CD Projekt Red', 'CD Projekt', 2015, '18', 'Single-player', 'RPG de mundo aberto estrelado por Geralt de Rivia em busca de Ciri.'),
('Bloodborne', 'RPG de Acao', 'FromSoftware', 'Sony Computer Entertainment', 2015, '16', 'Single-player e Online', 'RPG de acao gotico com combate agressivo e ambientacao lovecraftiana.'),
('Metal Gear Solid V: The Phantom Pain', 'Acao e Furtividade', 'Kojima Productions', 'Konami', 2015, '16', 'Single-player', 'Jogo de infiltracao em mundo aberto com missoes abertas e gestao de base.'),
('Undertale', 'RPG', 'Toby Fox', 'Toby Fox', 2015, '10', 'Single-player', 'RPG indie em que o jogador pode poupar ou enfrentar inimigos.'),
('Rocket League', 'Esporte', 'Psyonix', 'Psyonix', 2015, 'Livre', 'Single-player e Multiplayer', 'Futebol com carros impulsionados por foguete e foco competitivo.'),
('Life is Strange', 'Aventura', 'Dontnod Entertainment', 'Square Enix', 2015, '16', 'Single-player', 'Aventura narrativa com escolhas e poder de voltar no tempo.'),
('Splatoon', 'Tiro em Terceira Pessoa', 'Nintendo EAD', 'Nintendo', 2015, 'Livre', 'Single-player e Multiplayer', 'Tiro competitivo da Nintendo com tinta e transformacao em lula.'),
('Ori and the Blind Forest', 'Plataforma', 'Moon Studios', 'Microsoft Studios', 2015, 'Livre', 'Single-player', 'Metroidvania emocional com visual pintado e trilha orquestrada.'),
('Fallout 4', 'RPG de Acao', 'Bethesda Game Studios', 'Bethesda Softworks', 2015, '18', 'Single-player', 'RPG pos-apocaliptico em Boston com criacao de assentamentos.'),
('Overwatch', 'Tiro em Primeira Pessoa', 'Blizzard Entertainment', 'Blizzard Entertainment', 2016, '12', 'Online Multiplayer', 'Hero shooter em equipes com personagens de habilidades distintas.'),
('Uncharted 4: A Thief''s End', 'Acao e Aventura', 'Naughty Dog', 'Sony Interactive Entertainment', 2016, '14', 'Single-player e Multiplayer', 'Conclusao da historia de Nathan Drake com acao cinematografica.'),
('Dark Souls III', 'RPG de Acao', 'FromSoftware', 'Bandai Namco Entertainment', 2016, '16', 'Single-player e Online', 'Terceiro Dark Souls com combate mais rapido e encerramento tematico da serie.'),
('DOOM', 'Tiro em Primeira Pessoa', 'id Software', 'Bethesda Softworks', 2016, '18', 'Single-player e Multiplayer', 'Reinicio moderno da serie Doom com combate veloz e agressivo.'),
('Stardew Valley', 'Simulacao', 'ConcernedApe', 'ConcernedApe', 2016, 'Livre', 'Single-player e Multiplayer', 'Simulador de fazenda, relacionamentos, mineracao e vida comunitaria.'),
('Inside', 'Puzzle e Plataforma', 'Playdead', 'Playdead', 2016, '16', 'Single-player', 'Puzzle-plataforma sombrio com narrativa ambiental e atmosfera opressiva.'),
('Pokemon Go', 'Realidade Aumentada', 'Niantic', 'Niantic', 2016, 'Livre', 'Online Multiplayer', 'Jogo mobile de realidade aumentada para capturar Pokemon no mundo real.'),
('Final Fantasy XV', 'RPG de Acao', 'Square Enix Business Division 2', 'Square Enix', 2016, '14', 'Single-player', 'RPG de acao em mundo aberto com Noctis e seus companheiros.'),
('Persona 5', 'RPG', 'P-Studio', 'Atlus', 2016, '16', 'Single-player', 'RPG japones que combina vida escolar, palacios psicologicos e combate por turnos.'),
('The Legend of Zelda: Breath of the Wild', 'Aventura', 'Nintendo EPD', 'Nintendo', 2017, '10', 'Single-player', 'Aventura em mundo aberto com fisica, exploracao livre e sobrevivencia leve.'),
('Super Mario Odyssey', 'Plataforma', 'Nintendo EPD', 'Nintendo', 2017, 'Livre', 'Single-player', 'Plataforma 3D em que Mario usa Cappy para capturar inimigos e objetos.'),
('Horizon Zero Dawn', 'RPG de Acao', 'Guerrilla Games', 'Sony Interactive Entertainment', 2017, '14', 'Single-player', 'Aventura de acao em mundo aberto com maquinas e protagonista Aloy.'),
('Nier: Automata', 'RPG de Acao', 'PlatinumGames', 'Square Enix', 2017, '16', 'Single-player', 'RPG de acao filosofico com androides, maquinas e multiplas rotas narrativas.'),
('Fortnite Battle Royale', 'Battle Royale', 'Epic Games', 'Epic Games', 2017, '12', 'Online Multiplayer', 'Battle royale gratuito com construcao, temporadas e eventos ao vivo.'),
('PlayerUnknown''s Battlegrounds', 'Battle Royale', 'PUBG Studios', 'Krafton', 2017, '16', 'Online Multiplayer', 'Battle royale realista que popularizou o genero em larga escala.'),
('Cuphead', 'Run and Gun', 'Studio MDHR', 'Studio MDHR', 2017, '10', 'Single-player e Multiplayer', 'Run and gun com visual inspirado em desenhos animados dos anos 1930.'),
('Resident Evil 7: Biohazard', 'Survival Horror', 'Capcom', 'Capcom', 2017, '18', 'Single-player', 'Retorno ao terror com perspectiva em primeira pessoa e familia Baker.'),
('Prey', 'RPG de Acao', 'Arkane Studios', 'Bethesda Softworks', 2017, '18', 'Single-player', 'Imersive sim em estacao espacial com alienigenas Typhon e escolhas de abordagem.'),
('Divinity: Original Sin II', 'RPG', 'Larian Studios', 'Larian Studios', 2017, '16', 'Single-player e Multiplayer', 'RPG isometrico com combate tatico por turnos e grande liberdade narrativa.'),
('God of War', 'Acao e Aventura', 'Santa Monica Studio', 'Sony Interactive Entertainment', 2018, '18', 'Single-player', 'Reinicio nordico da serie, com Kratos e Atreus em jornada familiar.'),
('Red Dead Redemption 2', 'Acao e Aventura', 'Rockstar Studios', 'Rockstar Games', 2018, '18', 'Single-player e Online', 'Mundo aberto de faroeste com Arthur Morgan e a gangue Van der Linde.'),
('Marvel''s Spider-Man', 'Acao e Aventura', 'Insomniac Games', 'Sony Interactive Entertainment', 2018, '12', 'Single-player', 'Aventura de mundo aberto com o Homem-Aranha em Nova York.'),
('Celeste', 'Plataforma', 'Maddy Makes Games', 'Maddy Makes Games', 2018, '10', 'Single-player', 'Plataforma de precisao sobre escalar uma montanha e lidar com ansiedade.'),
('Monster Hunter: World', 'RPG de Acao', 'Capcom', 'Capcom', 2018, '14', 'Single-player e Multiplayer', 'RPG de acao cooperativo focado em cacar monstros gigantes.'),
('Super Smash Bros. Ultimate', 'Luta', 'Bandai Namco Studios / Sora Ltd.', 'Nintendo', 2018, '10', 'Single-player e Multiplayer', 'Crossover de luta com elenco extremamente amplo de personagens.'),
('Hades', 'Roguelike', 'Supergiant Games', 'Supergiant Games', 2020, '14', 'Single-player', 'Roguelike de acao com Zagreus tentando escapar do submundo grego.'),
('Apex Legends', 'Battle Royale', 'Respawn Entertainment', 'Electronic Arts', 2019, '14', 'Online Multiplayer', 'Battle royale em equipes com herois, habilidades e movimentacao rapida.'),
('Sekiro: Shadows Die Twice', 'Acao e Aventura', 'FromSoftware', 'Activision', 2019, '18', 'Single-player', 'Acao focada em espadas, postura e precisao em ambientacao japonesa.'),
('Resident Evil 2', 'Survival Horror', 'Capcom', 'Capcom', 2019, '18', 'Single-player', 'Remake moderno do classico de 1998 com nova camera e visual atualizado.'),
('Death Stranding', 'Acao e Aventura', 'Kojima Productions', 'Sony Interactive Entertainment', 2019, '16', 'Single-player e Online', 'Aventura sobre conexoes, entregas e isolamento em um mundo fragmentado.'),
('Control', 'Acao e Aventura', 'Remedy Entertainment', '505 Games', 2019, '16', 'Single-player', 'Acao sobrenatural em uma agencia federal cheia de fenomenos anormais.'),
('Fire Emblem: Three Houses', 'RPG Tatico', 'Intelligent Systems / Koei Tecmo', 'Nintendo', 2019, '12', 'Single-player', 'RPG tatico com escola militar, relacoes sociais e campanhas ramificadas.'),
('Disco Elysium', 'RPG', 'ZA/UM', 'ZA/UM', 2019, '18', 'Single-player', 'RPG narrativo investigativo com enfase em dialogos, ideologia e habilidades mentais.'),
('The Outer Worlds', 'RPG de Acao', 'Obsidian Entertainment', 'Private Division', 2019, '16', 'Single-player', 'RPG de ficcao cientifica com escolhas e satira corporativa.'),
('Animal Crossing: New Horizons', 'Simulacao', 'Nintendo EPD', 'Nintendo', 2020, 'Livre', 'Single-player e Multiplayer', 'Simulador social em ilha deserta com construcao, decoracao e vida comunitaria.'),
('The Last of Us Part II', 'Acao e Aventura', 'Naughty Dog', 'Sony Interactive Entertainment', 2020, '18', 'Single-player', 'Sequencia dramatica focada em vinganca, trauma e sobrevivencia.'),
('Ghost of Tsushima', 'Acao e Aventura', 'Sucker Punch Productions', 'Sony Interactive Entertainment', 2020, '16', 'Single-player', 'Aventura samurai em mundo aberto durante a invasao mongol de Tsushima.'),
('Doom Eternal', 'Tiro em Primeira Pessoa', 'id Software', 'Bethesda Softworks', 2020, '18', 'Single-player e Multiplayer', 'Sequencia de Doom com combate ainda mais rapido e gerenciamento agressivo de recursos.'),
('Final Fantasy VII Remake', 'RPG de Acao', 'Square Enix Business Division 1', 'Square Enix', 2020, '14', 'Single-player', 'Reimaginacao da primeira parte de Final Fantasy VII com combate hibrido.'),
('Cyberpunk 2077', 'RPG de Acao', 'CD Projekt Red', 'CD Projekt', 2020, '18', 'Single-player', 'RPG de mundo aberto ambientado em Night City, com escolhas e implantes ciberneticos.'),
('Valorant', 'Tiro em Primeira Pessoa', 'Riot Games', 'Riot Games', 2020, '14', 'Online Multiplayer', 'FPS tatico competitivo com agentes e habilidades especiais.'),
('Among Us', 'Dedução Social', 'InnerSloth', 'InnerSloth', 2018, 'Livre', 'Online Multiplayer', 'Jogo social de tripulantes e impostores em naves e bases.'),
('Ori and the Will of the Wisps', 'Plataforma', 'Moon Studios', 'Xbox Game Studios', 2020, 'Livre', 'Single-player', 'Sequencia de Ori com combate refinado, exploracao e narrativa emocional.'),
('Microsoft Flight Simulator', 'Simulacao', 'Asobo Studio', 'Xbox Game Studios', 2020, 'Livre', 'Single-player e Online', 'Simulador de voo com dados geograficos reais e clima dinamico.'),
('Demon''s Souls', 'RPG de Acao', 'Bluepoint Games', 'Sony Interactive Entertainment', 2020, '16', 'Single-player e Online', 'Remake do classico de PS3 com visual moderno para PlayStation 5.'),
('Ratchet & Clank: Rift Apart', 'Plataforma', 'Insomniac Games', 'Sony Interactive Entertainment', 2021, '10', 'Single-player', 'Aventura interdimensional com uso intenso do SSD do PlayStation 5.'),
('Returnal', 'Tiro em Terceira Pessoa', 'Housemarque', 'Sony Interactive Entertainment', 2021, '16', 'Single-player', 'Roguelike de tiro em terceira pessoa com narrativa de ficcao cientifica.'),
('It Takes Two', 'Aventura e Plataforma', 'Hazelight Studios', 'Electronic Arts', 2021, '10', 'Cooperativo', 'Aventura cooperativa obrigatoria sobre um casal transformado em bonecos.'),
('Forza Horizon 5', 'Corrida', 'Playground Games', 'Xbox Game Studios', 2021, 'Livre', 'Single-player e Multiplayer', 'Jogo de corrida em mundo aberto ambientado no Mexico.'),
('Metroid Dread', 'Acao e Aventura', 'MercurySteam / Nintendo EPD', 'Nintendo', 2021, '12', 'Single-player', 'Metroidvania lateral com Samus enfrentando robos E.M.M.I.'),
('Halo Infinite', 'Tiro em Primeira Pessoa', '343 Industries', 'Xbox Game Studios', 2021, '16', 'Single-player e Multiplayer', 'Novo capitulo de Halo com campanha semiaberta e multiplayer gratuito.'),
('Resident Evil Village', 'Survival Horror', 'Capcom', 'Capcom', 2021, '18', 'Single-player', 'Sequencia de Resident Evil 7 com vila europeia, monstros e castelo.'),
('Psychonauts 2', 'Plataforma', 'Double Fine Productions', 'Xbox Game Studios', 2021, '12', 'Single-player', 'Sequencia de Psychonauts com mundos mentais criativos e narrativa emocional.'),
('Deathloop', 'Tiro em Primeira Pessoa', 'Arkane Lyon', 'Bethesda Softworks', 2021, '18', 'Single-player e Online', 'FPS de loop temporal com assassinatos planejados e invasao de jogadores.'),
('Elden Ring', 'RPG de Acao', 'FromSoftware', 'Bandai Namco Entertainment', 2022, '16', 'Single-player e Online', 'RPG de acao em mundo aberto com combates desafiadores e exploracao livre.'),
('God of War Ragnarok', 'Acao e Aventura', 'Santa Monica Studio', 'Sony Interactive Entertainment', 2022, '18', 'Single-player', 'Continuação da saga nordica de Kratos e Atreus durante o Ragnarok.'),
('Horizon Forbidden West', 'RPG de Acao', 'Guerrilla Games', 'Sony Interactive Entertainment', 2022, '14', 'Single-player', 'Sequencia de Horizon com novas maquinas, tribos e exploracao do Oeste Proibido.'),
('Gran Turismo 7', 'Corrida', 'Polyphony Digital', 'Sony Interactive Entertainment', 2022, 'Livre', 'Single-player e Multiplayer', 'Simulador de corrida com campanha, colecionismo de carros e competicoes online.'),
('Pokemon Legends: Arceus', 'RPG', 'Game Freak', 'Nintendo', 2022, 'Livre', 'Single-player', 'RPG de Pokemon com exploracao aberta na antiga regiao de Hisui.'),
('Kirby and the Forgotten Land', 'Plataforma', 'HAL Laboratory', 'Nintendo', 2022, 'Livre', 'Single-player e Cooperativo', 'Primeira grande aventura 3D de Kirby em um mundo abandonado.'),
('Stray', 'Aventura', 'BlueTwelve Studio', 'Annapurna Interactive', 2022, '10', 'Single-player', 'Aventura em que o jogador controla um gato em uma cidade cyberpunk.'),
('Xenoblade Chronicles 3', 'RPG', 'Monolith Soft', 'Nintendo', 2022, '12', 'Single-player', 'RPG japones de mundo aberto com guerra entre nacoes e combate em grupo.'),
('Bayonetta 3', 'Acao', 'PlatinumGames', 'Nintendo', 2022, '16', 'Single-player', 'Jogo de acao estilosa estrelado por Bayonetta contra ameacas multiversais.'),
('Splatoon 3', 'Tiro em Terceira Pessoa', 'Nintendo EPD', 'Nintendo', 2022, 'Livre', 'Single-player e Multiplayer', 'Tiro competitivo com tinta, novas armas, campanha e modo Salmon Run.'),
('The Callisto Protocol', 'Survival Horror', 'Striking Distance Studios', 'Krafton', 2022, '18', 'Single-player', 'Terror espacial em prisao lunar com combate corpo a corpo e criaturas mutantes.'),
('The Legend of Zelda: Tears of the Kingdom', 'Aventura', 'Nintendo EPD', 'Nintendo', 2023, '10', 'Single-player', 'Aventura em mundo aberto com exploracao, construcao, ilhas celestes e combate.'),
('Baldur''s Gate 3', 'RPG', 'Larian Studios', 'Larian Studios', 2023, '16', 'Single-player e Multiplayer', 'RPG baseado em Dungeons & Dragons com combate por turnos e escolhas extensas.'),
('Starfield', 'RPG', 'Bethesda Game Studios', 'Bethesda Softworks', 2023, '16', 'Single-player', 'RPG espacial com exploracao de planetas, naves e faccoes.'),
('Marvel''s Spider-Man 2', 'Acao e Aventura', 'Insomniac Games', 'Sony Interactive Entertainment', 2023, '14', 'Single-player', 'Sequencia com Peter Parker e Miles Morales enfrentando novas ameacas em Nova York.'),
('Alan Wake 2', 'Survival Horror', 'Remedy Entertainment', 'Epic Games Publishing', 2023, '18', 'Single-player', 'Terror narrativo com duas campanhas envolvendo Alan Wake e Saga Anderson.'),
('Resident Evil 4', 'Survival Horror', 'Capcom', 'Capcom', 2023, '18', 'Single-player', 'Remake moderno de Resident Evil 4 com combate e ambientacao atualizados.'),
('Street Fighter 6', 'Luta', 'Capcom', 'Capcom', 2023, '12', 'Single-player e Multiplayer', 'Jogo de luta com World Tour, Battle Hub e novo sistema Drive.'),
('Mortal Kombat 1', 'Luta', 'NetherRealm Studios', 'Warner Bros. Games', 2023, '18', 'Single-player e Multiplayer', 'Reinicio da linha temporal de Mortal Kombat com sistema de Kameo Fighters.'),
('Diablo IV', 'RPG de Acao', 'Blizzard Entertainment', 'Blizzard Entertainment', 2023, '18', 'Single-player e Online', 'RPG de acao online em Santuário com mundo compartilhado e classes classicas.'),
('Final Fantasy XVI', 'RPG de Acao', 'Square Enix Creative Business Unit III', 'Square Enix', 2023, '16', 'Single-player', 'RPG de acao em Valisthea com conflitos politicos e Eikons.'),
('Pikmin 4', 'Estrategia', 'Nintendo EPD', 'Nintendo', 2023, 'Livre', 'Single-player', 'Nova aventura de Pikmin com resgate, exploracao e cachorro espacial Oatchi.'),
('Super Mario Bros. Wonder', 'Plataforma', 'Nintendo EPD', 'Nintendo', 2023, 'Livre', 'Single-player e Multiplayer', 'Plataforma 2D de Mario com efeitos Wonder e fases criativas.'),
('Armored Core VI: Fires of Rubicon', 'Acao', 'FromSoftware', 'Bandai Namco Entertainment', 2023, '12', 'Single-player e Multiplayer', 'Acao com mechas personalizaveis, missoes e combates intensos.'),
('Hi-Fi Rush', 'Acao e Ritmo', 'Tango Gameworks', 'Bethesda Softworks', 2023, '12', 'Single-player', 'Acao ritmica com combate sincronizado a musica e visual cartunesco.'),
('Sea of Stars', 'RPG', 'Sabotage Studio', 'Sabotage Studio', 2023, '10', 'Single-player', 'RPG inspirado em classicos dos anos 1990 com combate por turnos.'),
('Palworld', 'Sobrevivencia', 'Pocketpair', 'Pocketpair', 2024, '12', 'Single-player e Multiplayer', 'Jogo de sobrevivencia e colecao de criaturas com construcao e combate.'),
('Tekken 8', 'Luta', 'Bandai Namco Studios', 'Bandai Namco Entertainment', 2024, '12', 'Single-player e Multiplayer', 'Jogo de luta 3D com sistema Heat e continuidade da saga Mishima.'),
('Final Fantasy VII Rebirth', 'RPG de Acao', 'Square Enix Creative Business Unit I', 'Square Enix', 2024, '14', 'Single-player', 'Segunda parte do projeto Remake de Final Fantasy VII, com areas abertas e novos eventos.'),
('Dragon''s Dogma 2', 'RPG de Acao', 'Capcom', 'Capcom', 2024, '16', 'Single-player', 'RPG de acao em mundo aberto com sistema de peoes e combate contra monstros grandes.'),
('Helldivers 2', 'Tiro em Terceira Pessoa', 'Arrowhead Game Studios', 'Sony Interactive Entertainment', 2024, '18', 'Online Cooperativo', 'Tiro cooperativo em que jogadores espalham democracia gerenciada pela galaxia.'),
('Prince of Persia: The Lost Crown', 'Acao e Plataforma', 'Ubisoft Montpellier', 'Ubisoft', 2024, '12', 'Single-player', 'Metroidvania moderno da serie Prince of Persia com combate rapido e poderes temporais.'),
('Like a Dragon: Infinite Wealth', 'RPG', 'Ryu Ga Gotoku Studio', 'Sega', 2024, '18', 'Single-player', 'RPG por turnos com Ichiban Kasuga e Kazuma Kiryu em aventura no Havai.'),
('Senua''s Saga: Hellblade II', 'Acao e Aventura', 'Ninja Theory', 'Xbox Game Studios', 2024, '18', 'Single-player', 'Aventura cinematografica focada em psicose, mitologia nordica e captura de performance.'),
('Astro Bot', 'Plataforma', 'Team Asobi', 'Sony Interactive Entertainment', 2024, 'Livre', 'Single-player', 'Plataforma 3D estrelado por Astro, com fases criativas e referencias a franquias PlayStation.'),
('Black Myth: Wukong', 'RPG de Acao', 'Game Science', 'Game Science', 2024, '16', 'Single-player', 'RPG de acao inspirado em Jornada ao Oeste, com combates contra chefes e mitologia chinesa.'),
('The Legend of Zelda: Echoes of Wisdom', 'Aventura', 'Grezzo / Nintendo', 'Nintendo', 2024, '10', 'Single-player', 'Aventura estrelada pela Princesa Zelda usando ecos para resolver puzzles e enfrentar inimigos.'),
('Indiana Jones and the Great Circle', 'Acao e Aventura', 'MachineGames', 'Bethesda Softworks', 2024, '16', 'Single-player', 'Aventura em primeira pessoa baseada em Indiana Jones, com exploracao e combate.'),
('Mario & Luigi: Brothership', 'RPG', 'Acquire', 'Nintendo', 2024, 'Livre', 'Single-player', 'RPG da serie Mario & Luigi com combates por comando e aventura em ilhas.'),
('Silent Hill 2', 'Survival Horror', 'Bloober Team', 'Konami', 2024, '18', 'Single-player', 'Remake do classico de terror psicologico da Konami.'),
('Metaphor: ReFantazio', 'RPG', 'Studio Zero', 'Atlus', 2024, '16', 'Single-player', 'RPG de fantasia dos criadores modernos de Persona com combate hibrido e calendario.'),
('Balatro', 'Roguelike e Cartas', 'LocalThunk', 'Playstack', 2024, '12', 'Single-player', 'Roguelike de cartas baseado em poker com combinacoes e multiplicadores.'),
('Hades II', 'Roguelike', 'Supergiant Games', 'Supergiant Games', 2024, '14', 'Single-player', 'Sequencia de Hades estrelada por Melinoe contra Cronos.'),
('Marvel Rivals', 'Tiro em Terceira Pessoa', 'NetEase Games', 'NetEase Games', 2024, '12', 'Online Multiplayer', 'Hero shooter em equipes com personagens da Marvel e ambientes destrutiveis.'),
('EA Sports FC 24', 'Esporte', 'EA Vancouver / EA Romania', 'Electronic Arts', 2023, 'Livre', 'Single-player e Multiplayer', 'Jogo de futebol que sucedeu a serie FIFA da EA Sports.'),
('EA Sports FC 25', 'Esporte', 'EA Vancouver / EA Romania', 'Electronic Arts', 2024, 'Livre', 'Single-player e Multiplayer', 'Jogo anual de futebol da EA com clubes licenciados e modos online.'),
('Call of Duty: Black Ops 6', 'Tiro em Primeira Pessoa', 'Treyarch / Raven Software', 'Activision', 2024, '18', 'Single-player e Multiplayer', 'Capitulo da subserie Black Ops com campanha, multiplayer e Zombies.'),
('Assassin''s Creed Mirage', 'Acao e Aventura', 'Ubisoft Bordeaux', 'Ubisoft', 2023, '16', 'Single-player', 'Aventura de Assassin''s Creed com retorno ao foco em furtividade e parkour.'),
('Forza Motorsport', 'Corrida', 'Turn 10 Studios', 'Xbox Game Studios', 2023, 'Livre', 'Single-player e Multiplayer', 'Reinicio da serie Forza Motorsport com foco em simulacao e competicao.'),
('Cities: Skylines II', 'Simulacao', 'Colossal Order', 'Paradox Interactive', 2023, 'Livre', 'Single-player', 'Simulador de construcao e gestao de cidades com sistemas urbanos detalhados.'),
('Lethal Company', 'Survival Horror', 'Zeekerss', 'Zeekerss', 2023, '14', 'Online Cooperativo', 'Terror cooperativo em que jogadores coletam sucata em luas perigosas.'),
('Lies of P', 'RPG de Acao', 'Neowiz Games / Round8 Studio', 'Neowiz Games', 2023, '16', 'Single-player', 'Soulslike inspirado em Pinocchio com ambientacao sombria e combate tecnico.');

SET FOREIGN_KEY_CHECKS = 1;